openapi: 3.0.2
info:
  title: bookings
  version: 1.0.0
paths: {}
components:
  schemas:
    BookingCreateActivity:
      type: object
      properties:
        base_data:
          type: object
          properties:
            cnt_language:
              description: ISO 639, Language of the text content.
              type: string
              example: "en"
            currency:
              description: ISO 4217, The currency with which you would like to pay.
              type: string
              example: "EUR"
        data:
          type: object
          properties:
            booking:
              type: object
              properties:
                coupon:
                  type: object
                  properties:
                    coupon_code:
                      type: string
                      example: 123ABC
                bookable:
                  type: object
                  properties:
                    option_id:
                      $ref: '../commons.yaml#/components/schemas/OptionId'
                    datetime:
                      $ref: '../commons.yaml#/components/schemas/Datetime'
                    price:
                      type: string
                      example: '170.00'
                    categories:
                      type: array
                      items:
                        type: object
                        properties:
                          category_id:
                            type: string
                            example: '2077534'
                          number_of_participants:
                            type: string
                            example: '5'
                    booking_parameters:
                      $ref: '../schema/bookings.yaml#/components/schemas/BookingParameters'


    BookingCreateCoupon:
      type: object
      properties:
        base_data:
          type: object
          properties:
            cnt_language:
              description: ISO 639, Language of the text content.
              type: string
              example: "en"
            currency:
              description: ISO 4217, The currency with which you would like to pay.
              type: string
              example: "EUR"
        data:
          type: object
          properties:
            booking:
              type: object
              properties:
                coupon:
                  type: object
                  properties:
                    coupon_code:
                      type: string
                      example: 123ABC

    BookingCreateResponse:
      type: object
      properties:
        bookings:
          type: object
          properties:
            shopping_cart_id:
              $ref: '../commons.yaml#/components/schemas/ShoppingCartId'
            shopping_cart_hash:
              $ref: '../commons.yaml#/components/schemas/ShoppingCartHash'
            booking_id:
              $ref: '../commons.yaml#/components/schemas/BookingId'
            booking_hash:
              $ref: '../commons.yaml#/components/schemas/BookingHash'
            booking_status:
              $ref: '../commons.yaml#/components/schemas/BookingStatus'
            return_code:
              $ref: '../commons.yaml#/components/schemas/ReturnCode'
    
    BookingsGetByHashResponse:
      type: object
      properties:
        bookings:
          $ref: '#/components/schemas/Bookings'

    BookingDeleteResponse:
      type: object
      properties:
        bookings:
          type: object
          properties:
            shopping_cart_id:
              $ref: '../commons.yaml#/components/schemas/ShoppingCartId'
            shopping_cart_hash:
              $ref: '../commons.yaml#/components/schemas/ShoppingCartHash'
            booking_id:
              $ref: '../commons.yaml#/components/schemas/BookingId'
            booking_hash:
              $ref: '../commons.yaml#/components/schemas/BookingHash'
            booking_status:
              $ref: '../commons.yaml#/components/schemas/BookingStatus'
            return_code:
              $ref: '../commons.yaml#/components/schemas/ReturnCode'
    
    Bookings:
      type: object
      properties:
        booking_id:
          $ref: '../commons.yaml#/components/schemas/BookingId'
        booking_hash:
          $ref: '../commons.yaml#/components/schemas/BookingHash'
        booking_status:
          $ref: '../commons.yaml#/components/schemas/BookingStatus'
        shopping_cart_id:
          $ref: '../commons.yaml#/components/schemas/ShoppingCartId'
        shopping_cart_hash:
          $ref: '../commons.yaml#/components/schemas/ShoppingCartHash'
        bookable:
          $ref: '#/components/schemas/Bookable'

    Bookable:
      type: object
      properties:
        tour_id:
          $ref: '../commons.yaml#/components/schemas/TourId'
        option_id:
          $ref: '../commons.yaml#/components/schemas/OptionId'
        datetime:
          $ref: '../commons.yaml#/components/schemas/Datetime'
        datetime_utc:
          $ref: '../commons.yaml#/components/schemas/DatetimeUTC'
        datetime_type:
          $ref: '../commons.yaml#/components/schemas/DatetimeType'
        opening_hours:
          type: array
          items:
            type: object
            properties:
              opening_time:
                $ref: '../commons.yaml#/components/schemas/Datetime'
              closing_time:
                $ref: '../commons.yaml#/components/schemas/Datetime'
        price:
          description: The price of the activity described in this bookable. You will have to calculate reduced prices yourself. The discount as a percentage value, if present, is retrieved from the options/availabilities endpoint.
          type: number
          format: double
          example: 270
        valid_until:
          $ref: '../commons.yaml#/components/schemas/Datetime'
        cancellation_policy_text:
          $ref: '../commons.yaml#/components/schemas/CancellationPolicyText'
        currently_cancellable_at_no_fee:
          $ref: '../commons.yaml#/components/schemas/CurrentlyCancellableAtNoFee'
        categories:
          type: array
          description: The price categories used for this booking.
          items:
            type: object
            properties:
              category_id:
                type: number
                example: 302628
              name:
                type: string
                example: Adults
              number_of_participants: 
                type: number
                example: 1
        booking_parameters:
          $ref: '#/components/schemas/BookingParameters'

    BookingParameters:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            description: Name of the property
            enum: [language, hotel, comment, supplier_requested_question]
            example: language
          value_1:
            type: string
            description: First / Primary value of the property
            example: language_live
          value_2:
            type: string
            description: The language property requires a second value (e.g. value_1 = language_live, value_2 = en).
            example: en
          mandatory:
            type: boolean
            description: The mandatory booking parameters can be retrieved from the options endpoint
            example: false