openapi: 3.0.2
info:
  title: Bookings schema
  version: 1.0.0
paths: {}

components:
  schemas:
    BookingCreateActivity:
      type: object
      properties:
        base_data:
          type: object
          properties:
            cnt_language:
              $ref: "../commons/fields.yaml#/components/schemas/CntLanguage"
            currency:
              $ref: "../commons/fields.yaml#/components/schemas/Currency"
        data:
          type: object
          properties:
            booking:
              type: object
              description: The booking object, you may specify an already existing shopping cart the booking shall be added to. If no `shopping_cart_id` is specified a new cart is automatically created for the booking. 
              properties:
                shopping_cart_id:
                  $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartId"
                bookable:
                  type: object
                  properties:
                    external_reference_id:
                      $ref: "../commons/fields.yaml#/components/schemas/ExternalReferenceId"
                    option_id:
                      $ref: "../commons/fields.yaml#/components/schemas/OptionId"
                    datetime:
                      $ref: "../commons/fields.yaml#/components/schemas/Datetime"
                    price:
                      $ref: "../commons/fields.yaml#/components/schemas/PriceField"
                    categories:
                      type: array
                      items:
                        type: object
                        properties:
                          category_id:
                            $ref: ../commons/fields.yaml#/components/schemas/CategoryId
                          number_of_participants:
                            type: integer
                            example: 5
                        required:
                          - category_id
                          - number_of_participants
                    booking_parameters:
                      $ref: "../schema/bookings.yaml#/components/schemas/BookingParameters"
                  required:
                    - option_id
                    - datetime
                    - price
                    - categories
    RedeemCoupon:
      type: object
      properties:
        base_data:
          type: object
          properties:
            cnt_language:
              $ref: "../commons/fields.yaml#/components/schemas/CntLanguage"
            currency:
              $ref: "../commons/fields.yaml#/components/schemas/Currency"
        data:
          type: object
          properties:
            coupon:
              type: object
              properties:
                coupon_code:
                  type: string
                  example: 123ABC

    BookingCreateResponse:
      type: object
      properties:
        bookings:
          type: object
          properties:
            shopping_cart_id:
              $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartId"
            shopping_cart_hash:
              $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartHash"
            booking_id:
              $ref: "../commons/fields.yaml#/components/schemas/BookingId"
            booking_hash:
              $ref: "../commons/fields.yaml#/components/schemas/BookingHash"
            status:
              $ref: "../commons/fields.yaml#/components/schemas/BookingStatus"
            return_code:
              $ref: "../commons/fields.yaml#/components/schemas/ReturnCode"

    BookingsGetByHashResponse:
      type: object
      properties:
        booking:
          $ref: "#/components/schemas/Booking"

    BookingDeleteResponse:
      type: object
      properties:
        bookings:
          type: object
          properties:
            shopping_cart_id:
              $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartId"
            shopping_cart_hash:
              $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartHash"
            booking_id:
              $ref: "../commons/fields.yaml#/components/schemas/BookingId"
            booking_hash:
              $ref: "../commons/fields.yaml#/components/schemas/BookingHash"
            booking_status:
              $ref: "../commons/fields.yaml#/components/schemas/BookingStatus"
            return_code:
              $ref: "../commons/fields.yaml#/components/schemas/ReturnCode"

    Booking:
      type: object
      properties:
        booking_id:
          $ref: "../commons/fields.yaml#/components/schemas/BookingId"
        booking_hash:
          $ref: "../commons/fields.yaml#/components/schemas/BookingHash"
        booking_status:
          $ref: "../commons/fields.yaml#/components/schemas/BookingStatus"
        shopping_cart_id:
          $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartId"
        shopping_cart_hash:
          $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartHash"
        bookable:
          $ref: "#/components/schemas/Bookable"
        ticket:
          description: Only present if the booking is confirmed and active.
          $ref: "#/components/schemas/Ticket"

    Bookable:
      type: object
      properties:
        tour_id:
          $ref: "../commons/fields.yaml#/components/schemas/TourId"
        option_id:
          $ref: "../commons/fields.yaml#/components/schemas/OptionId"
        datetime:
          $ref: "../commons/fields.yaml#/components/schemas/Datetime"
        datetime_utc:
          $ref: "../commons/fields.yaml#/components/schemas/DatetimeUTC"
        datetime_type:
          $ref: "../commons/fields.yaml#/components/schemas/DatetimeType"
        opening_hours:
          type: array
          items:
            type: object
            properties:
              opening_time:
                $ref: "../commons/fields.yaml#/components/schemas/Datetime"
              closing_time:
                $ref: "../commons/fields.yaml#/components/schemas/Datetime"
        price:
          $ref: "../commons/fields.yaml#/components/schemas/PriceField"
        valid_until:
          $ref: "../commons/fields.yaml#/components/schemas/Datetime"
        cancellation_policy_text:
          $ref: "../commons/fields.yaml#/components/schemas/CancellationPolicyText"
        currently_cancellable_at_no_fee:
          $ref: "../commons/fields.yaml#/components/schemas/CurrentlyCancellableAtNoFee"
        categories:
          type: array
          description: The price categories used for this booking.
          items:
            type: object
            properties:
              category_id:
                $ref: ../commons/fields.yaml#/components/schemas/CategoryId
              name:
                type: string
                example: Adults
              number_of_participants:
                type: integer
                example: 1
        booking_parameters:
          $ref: "#/components/schemas/BookingParameters"

    BookingParameters:
      description: The mandatory booking parameters are specific to a given tour option and can be retrieved from `GET /options/{option_id}`
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            description: Name of the property
            enum: [language, hotel, comment, supplier_requested_question]
            example: language
          value_1:
            type: string
            description: First / Primary value of the property
            example: language_live
          value_2:
            type: string
            description: The language property requires a second value (e.g. value_1 = language_live, value_2 = en).
            example: en
          mandatory:
            type: boolean
            description: The mandatory booking parameters can be retrieved from the options endpoint
            example: true

    Ticket:
      type: object
      properties:
        booking_reference:
          type: string
          example: GYG7VMWR9HZ3
        supplier_booking_codes:
          $ref: "#/components/schemas/SupplierBookingCodes"
        emergency_phone_number:
          $ref: "../commons/fields.yaml#/components/schemas/PhoneNumber"
        emergency_email:
          $ref: "../commons/fields.yaml#/components/schemas/Email"
        ticket_url:
          type: string
          format: uri
          description: Download link for ticket PDF
          example: https://www.getyourguide.com/voucher/7H8N87D3QAH16XVABGPCR311U66XELRG
        ticket_hash:
          type: string
          example: 7H8N87D3QAH16XVABGPCR311U66XELRG

    SupplierBookingCodes:
      type: array
      items:
        type: object
        properties:
          ticket_hash:
            type: string
            example: 7H8N87D3QAH16XVABGPCR311U66XELRG
          label:
            type: string
            example: "Ticket #1 (ADULT)"
          type:
            description: The encoding algorithm used for the bar/qr code.
            type: string
            example: qr_code
            enum:
              - text
              - barcode_code39
              - barcode_code128
              - qr_code
              - data_matrix
              - ean13
              - itf
              - pdf_file
              - code25interleaved
              - aztec
          code:
            description: The sting that will be encoded into the barcode.
            type: string
            example: JRUFX567YOMTSI7RG5K3UL2XC6RECSGQ-E9VNO
          pricing_category_id:
            type: integer
            example: 2167696
