openapi: 3.0.2
info:
  title: bookings
  version: 1.0.0
paths: {}
components:
  schemas:
    CartsConfirmRequest:
      type: object
      properties:
        base_data:
          type: object
          properties:
            cnt_language:
              $ref: "../commons/fields.yaml#/components/schemas/CntLanguage"
            currency:
              $ref: "../commons/fields.yaml#/components/schemas/Currency"
        data:
          type: object
          properties:
            shopping_cart:
              type: object
              properties:
                shopping_cart_id:
                  $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartId"
                shopping_cart_hash:
                  $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartHash"
                billing:
                  $ref: "#/components/schemas/Billing"
                traveler:
                  $ref: "#/components/schemas/Traveler"
                payment:
                  oneOf:
                    - $ref: "./payment.yaml#/components/schemas/Paypal"
                    - $ref: "./payment.yaml#/components/schemas/EncryptedCreditCard"
                    - $ref: "./payment.yaml#/components/schemas/MasterBill"

    CartsConfirmResponseConfirmed:
      type: object
      properties:
        shopping_cart_id:
          $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartId"
        shopping_cart_hash:
          $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartHash"
        billing:
          $ref: "#/components/schemas/Billing"
        traveler:
          $ref: "#/components/schemas/Traveler"
        status:
          $ref: "#/components/schemas/Status"
        bookings:
          $ref: "../schema/bookings.yaml#/components/schemas/Booking"
        payment_info:
          $ref: "./payment.yaml#/components/schemas/PaymentInfoConfirmed"

    CartsConfirmResponseInPayment:
      type: object
      properties:
        shopping_cart_id:
          $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartId"
        shopping_cart_hash:
          $ref: "../commons/fields.yaml#/components/schemas/ShoppingCartHash"
        billing:
          $ref: "#/components/schemas/Billing"
        traveler:
          $ref: "#/components/schemas/Traveler"
        status:
          $ref: "#/components/schemas/Status"
        bookings:
          $ref: "../schema/bookings.yaml#/components/schemas/Booking"
        payment_process:
          $ref: "./payment.yaml#/components/schemas/PaymentProcess"
        payment_info:
          $ref: "./payment.yaml#/components/schemas/PaymentInfoInPayment"

    # Cart Objects
    Billing:
      type: object
      properties:
        salutation_code:
          $ref: "#/components/schemas/SalutationCode"
        first_name:
          $ref: "#/components/schemas/FirstName"
        last_name:
          $ref: "#/components/schemas/LastName"
        email:
          $ref: "../commons/fields.yaml#/components/schemas/Email"
        is_company:
          $ref: "#/components/schemas/IsCompany"
        company_name:
          $ref: "#/components/schemas/CompanyName"
        invoice:
          $ref: "#/components/schemas/Invoice"
        address_line_1:
          $ref: "#/components/schemas/AddressLine1"
        address_line_2:
          $ref: "#/components/schemas/AddressLine2"
        city:
          $ref: "#/components/schemas/City"
        postal_code:
          $ref: "#/components/schemas/PostalCode"
        state:
          $ref: "#/components/schemas/State"
        country_code:
          $ref: "../commons/fields.yaml#/components/schemas/Country"
        phone_number:
          $ref: "../commons/fields.yaml#/components/schemas/PhoneNumber"
      required:
        - first_name
        - last_name
        - email
        - country_code
        - phone_number

    Traveler:
      type: object
      properties:
        salutation_code:
          $ref: "#/components/schemas/SalutationCode"
        first_name:
          $ref: "#/components/schemas/FirstName"
        last_name:
          $ref: "#/components/schemas/LastName"
        email:
          $ref: "../commons/fields.yaml#/components/schemas/Email"
        phone_number:
          $ref: "../commons/fields.yaml#/components/schemas/PhoneNumber"
      required:
        - first_name
        - last_name
        - email
        - country_code
        - phone_number

    # Data fields in carts object:
    Status:
      type: string
      enum: ["completed", "open", "in_payment", "invalid"]
      description: >
        The status of the shopping cart:
          * `open`: the shopping cart is open and needs to be checked out
          * `completed`: the transaction is completed
          * `in_payment`: the transaction is ongoing, this status only occurs with 2-step checkout (PayPal or 3DS CC)
          * `invalid`: the shopping cart is invalid

    # Data fields for billing and traveler info
    AddressLine1:
      description: Street and house number.
      example: 1000 Fulton Avenue
      type: string
      maxLength: 44
    AddressLine2:
      description: Additional information which did not fit in the first row.
      example: c/o Amy Winter
      type: string
      maxLength: 44
    City:
      description: Name of the city.
      example: Berlin
      type: string
      maxLength: 44
    CompanyName:
      description: Name of the company.
      example: GetYourGuide
      type: string
      maxLength: 44
    FirstName:
      description: The first name
      example: John
      type: string
      maxLength: 44
    Invoice:
      description: Indicates wether an invoice is required for this purchase.
      example: false
      type: boolean
    IsCompany:
      description: Is the payee a company.
      example: false
      type: boolean
    LastName:
      description: The last name
      example: Doe
      type: string
      maxLength: 44
    PostalCode:
      description: Postal/zip code.
      example: "14050"
      type: string
      maxLength: 44
    SalutationCode:
      description: Salutation code. m=Mr. f=Mrs. c=empty
      enum:
        - m
        - f
        - c
      example: m
      type: string
    State:
      description: State within the country.
      example: California
      type: string
