openapi: 3.0.2
info:
  title: bookings
  version: 1.0.0
paths: {}
components:
  schemas:
    CartsConfirmRequest:
      type: object
      properties:
        base_data:
          type: object
          properties:
            cnt_language:
              description: ISO 639, Language of the text content.
              type: string
              example: "en"
            currency:
              description: ISO 4217, The currency with which you would like to pay.
              type: string
              example: "EUR"
        data:
          type: object
          properties:
            booking:
              type: object
              properties:
                bookable:
                  type: object
                  properties:
                    option_id:
                      $ref: '../commons.yaml#/components/schemas/OptionId'
                    datetime:
                      $ref: '../commons.yaml#/components/schemas/Datetime'
                    price:
                      type: string
                      example: '170.00'
                    categories:
                      type: array
                      items:
                        type: object
                        properties:
                          category_id:
                            type: string
                            example: '2077534'
                          number_of_participants:
                            type: string
                            example: '5'
                    booking_parameters:
                      $ref: '../commons.yaml#/components/schemas/BookingParameters'

    CartsConfirmResponse:
      type: object
      properties:
        bookings:
          type: object
          properties:
            shopping_cart_id:
              $ref: '../commons.yaml#/components/schemas/ShoppingCartId'
            shopping_cart_hash:
              $ref: '../commons.yaml#/components/schemas/ShoppingCartHash'
            booking_id:
              $ref: '../commons.yaml#/components/schemas/BookingId'
            booking_hash:
              $ref: '../commons.yaml#/components/schemas/BookingHash'
            booking_status:
              $ref: '../commons.yaml#/components/schemas/BookingStatus'
            return_code:
              $ref: '../commons.yaml#/components/schemas/ReturnCode'

    PaymentInfo:
      type: object
      properties:
        payment_currency:
          type: string
          description: The currency in which the payment has been processed.
          example: ERU
        total_price:
          type: number
          description: The total price of the shopping cart.
          example: 209.78
        precoupon_price:
          type: number
          description: The price of the shopping cart before coupons have been applied.
          example: 209.78
        payment_method:
          type: string
          description: The payment method used to pay.
          enum: ['cc', 'pp', 'dd', 'co', 'mb', 'mx', 'n/a']
          example: cc
        coupon_info:
          type: string
          description: The code of the coupon if one was used.
          example: test
        invoice_reference:
          type: string
          description: The invoice reference number.
          example: GCI-0032724458
    