openapi: 3.0.2
paths: {}
info:
  title: Category Schema
  version: 1.0.0
components:
  schemas:
    Category:
      type: object
      properties:
        category_id:
          $ref: ../commons/fields.yaml#/components/schemas/CategoryId
        name:
          type: string
          description: Name of the category.
          example: Theme Parks & Amusement Parks
        parent_id:
          type: number
          description: Id of the parent category (if there is any).
          example: 123
        number_of_tours:
          type: number
          description: Number of available tours in the category.
          example: 10
