openapi: 3.0.2
info:
  title: Configuration
  version: 1.0.0
paths: {}
components:
  schemas:
    ConfigurationVersionResponse:
      type: object
      properties:
        configuration:
          type: object
          properties:
            api_version:
              description: The active version of the API
              type: string
              example: "1"
            status:
              description: The current status of the API
              type: string
              example: "OK"
            url:
              description: The base URL of the API. Endpoints to be appended at the end
              type: string
              example: "https://api.getyourguide.com/1/"

    ConfigurationPaymentResponse:
      type: object
      properties:
        payment_methods:
          type: array
          items:
            type: object
            properties:
              name:
                description: The name of the payment method.
                type: string
                example: "encrypted_credit_card"
              public_key:
                description: Required parameter by the encryption library to encrypt the users credit card information.
                type: string
                example: "imagine_a_public_key"
              brands:
                description: List of credit card brands available, results vary depending on the country parameter passed.
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: integer
                      example: 0
                    name:
                      description: The name of the brand.
                      type: string
                      example: "VISA"

    ConfigurationPrivilegeResponse:
      type: object
      properties:
        privileges:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Privileges
                enum: [LIMITED_READ, READ, BOOKING, BOOKING_CANCEL]
                example: LIMITED_READ
