openapi: 3.0.2
paths: {}
info:
  title: Coordinates Schema
  version: 1.0.0
components:
  schemas:
    
    Coordinates:
      type: object
      properties:
        lat:
          type: number
          description: Latitude.
        long:
          type: number
          description: Longitude.