openapi: 3.0.2
paths: {}
info:
  title: Duration Schema
  version: 1.0.0
components:
  schemas:
    
    Duration:
      type: object
      properties:
        duration:
          type: number
          description: Duration value
          example: 2
        unit:
          type: string
          description: Unit of the duration field
          enum: [day, hour, minute]
          example: hour