openapi: 3.0.2
paths: {}
info:
  title: Location Schema
  version: 1.0.0
components:
  schemas:
    Location:
      type: object
      properties:
        location_id:
          description: Location ID
          type: number
          example: 3850
        type:
          description: Location type
          type: string
          enum: [area, city, poi]
          example: poi
        name:
          type: string
          description: Name of the location.
          example: Epcot Theme Park
        english_name:
          description: DEPRECATED, always the same `name`
          type: string
          example: Epcot Theme Park
        country:
          $ref: "../commons/fields.yaml#/components/schemas/Country"
        coordinates:
          $ref: "../commons/objects.yaml#/components/schemas/Coordinates"
        parent_id:
          description: The location id of the parent location, if there is any.
          type: integer
          example: 191

        # NOT PART OF RESPONSE
        # city:
        #   type: string
        #   description: The city name if location type is POI or CITY.
        #   example: Orlando
        # viewport:
        #   $ref: "../commons/objects.yaml#/components/schemas/Viewport"
        # picture:
        #   type: string
        #   format: uri
        #   example: https://cdn.getyourguide.com/img/location/5ffeb24865bf8.jpeg/[format_id].jpg
        # picture_ssh:
        #   type: string
        #   format: uri
        #   example: https://cdn.getyourguide.com/img/location/5ffeb24865bf8.jpeg/[format_id].jpg
        # num_tours:
        #   type: number
        #   format: integer
        #   example: 386
