openapi: 3.0.2
info:
  title: Metadata Schema
  version: 1.0.0
paths: {}
components:
  schemas:
    MetaData:
      name: MetaData
      type: object
      properties:
        descriptor:
          type: string
          example: GetYourGuide AG
        query:
          type: string
          description: URL parameters used for the request sent
          example: "cnt_language=en&currency=eur"
        availableLanguages:
          type: array
          description: Available conduction languages aggregated across all tours
          items:
            $ref: "../commons/fields.yaml#/components/schemas/Language"
          example: [en, es, fr]
        exchange:
          type: object
          description: Deprecated! Please do not use to calculate prices, but pass a different currency parameter in the request URL.
          properties:
            rate:
              type: integer
              example: 1
            currency:
              $ref: "../commons/fields.yaml#/components/schemas/Currency"
              example: EUR
        totalCount:
          type: integer
          description: Total amount of tours that match the search query
          example: 127
        limit:
          description: Amount of tours returned in the response.
          $ref: "../commons/fields.yaml#/components/schemas/Limit"
        offset:
          description: Offset of the tours returned in the response.
          $ref: "../commons/fields.yaml#/components/schemas/Offset"
