openapi: 3.0.2
info:
  title: Tour Schema
  version: 1.0.0
paths: {}
components:
  schemas:
    TourOption:
      description: Tour option
      type: object
      properties:
        option_id:
          $ref: "../commons/fields.yaml#/components/schemas/OptionId"
        tour_id:
          $ref: "../commons/fields.yaml#/components/schemas/TourId"
        title:
          type: string
          description: Title of the option.
          example: "From Abu Dhabi: Private Transfer to Dubai"
        description:
          type: string
          description: Description of the option.
        pick_up:
          type: string
          description: Information about the hotel pickup possibilities.
        meeting_point:
          type: string
          description: Information about where to meet.
        drop_off:
          type: string
          description: Information about the drop-off (where the tour ends).
        duration:
          $ref: "../commons/fields.yaml#/components/schemas/Duration"
        duration_unit:
          $ref: "../commons/fields.yaml#/components/schemas/DurationUnit"
        cond_language:
          type: object
          properties:
            language_audio:
              type: array
              items:
                $ref: "../commons/fields.yaml#/components/schemas/Language"
              description: List of languages that are available as audio guide
              example: [de, fr, es, ru]
            language_booklet:
              type: array
              items:
                $ref: "../commons/fields.yaml#/components/schemas/Language"
              description: List of languages that are available as booklet
              example: [de, fr, en]
            language_live:
              type: array
              items:
                $ref: "../commons/fields.yaml#/components/schemas/Language"
              description: List of languages that are spoken by the guide
              example: [de, en]
        booking_parameter:
          deprecated: true
          description: DEPRECATED! use questions instead
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of the booking parameter.
                enum: [language, hotel, comment, supplier_requested_question]
                example: supplier_requested_question
              description:
                type: string
                description: Description of the property.
                example: Please provide the client names, flight details, and pick up and drop-off location.
              mandatory:
                type: boolean
                description: Flag if this parameter / property is mandatory for booking.
                example: true
        questions:
          type: object
          properties:
            booking_questions:
              type: array
              items:
                type: object
                properties:
                  question:
                    type: string
                    description: Name of the question.
                    enum: [
                      booking_child_safety_seat,
                      booking_cruise_details,
                      booking_customer_accommodation,
                      booking_drop_off_address,
                      booking_flight_details,
                      booking_medical_conditions,
                      booking_mobility_issues,
                      booking_shipping_address,
                      booking_wheelchair
                    ]
                    example: booking_mobility_issues
                  description:
                    type: string
                    description: Description of the question.
                    example: Please provide the flight details of the booking.
                  mandatory:
                    type: boolean
                    description: Flag if this parameter / property is mandatory for booking.
                    example: true
            participant_questions:
              type: array
              items:
                type: object
                properties:
                  question:
                    type: string
                    description: Name of the question.
                    enum: [
                      traveler_dietary_restrictions,
                      traveler_diving_levels,
                      traveler_driver_licenses,
                      traveler_shoe_sizes,
                      traveler_skill_levels,
                      traveler_ages,
                      traveler_children_ages,
                      traveler_dates_of_birth,
                      traveler_heights,
                      traveler_id_details,
                      traveler_id_numbers,
                      traveler_names,
                      traveler_passport_details,
                      traveler_passport_numbers,
                      traveler_weights
                    ]
                    example: traveler_diving_levels
                  description:
                    type: string
                    description: Description of the question.
                    example: Please provide the traveler names for each participant in your group.
                  mandatory:
                    type: boolean
                    description: Flag if this parameter / property is mandatory for booking.
                    example: true
            conduction_language:
              type: object
              properties:
                mandatory:
                  type: boolean
                  description: Flag if this parameter / property is mandatory for booking.
                  example: true
            free_text_question:
              type: object
              properties:
                mandatory:
                  type: boolean
                  description: Flag if this parameter / property is mandatory for booking.
                  example: true
                description:
                  type: string
                  description: Description of the free-text-question.
                  example: Please provide the nationality of everyone in your group.
        services:
          type: object
          properties:
            prt:
              type: boolean
              description: If true, the option is closed after on booking. The customer will be on the tour without any other guests expect those included in the same booking.
              example: true
            stl:
              type: boolean
              description: If true, the customer does not need to wait in line.
              example: true
            wlc:
              type: boolean
              description: If true, there is wheel chair access.
              example: true
        coordinate_type:
          type: string
          description: Information about the type of the coordinates. It defines if the information is exactly enough for the customer to walk / get there.
          enum: [exact, approximate]
        coordinates:
          $ref: "../commons/objects.yaml#/components/schemas/Coordinates"
        price:
          oneOf:
            - $ref: "../commons/objects.yaml#/components/schemas/StartingPrice"
            - $ref: "../commons/objects.yaml#/components/schemas/StartingPriceDiscounted"
        free_sale:
          $ref: "../commons/fields.yaml#/components/schemas/FreeSale"
