openapi: 3.0.2
info:
  title: Tour Schema
  version: 1.0.0
paths: {}
components:
  schemas:
    TourOption:
      description: Tour option
      type: object
      properties:
        option_id:
          $ref: "../commons/fields.yaml#/components/schemas/OptionId"
        tour_id:
          $ref: "../commons/fields.yaml#/components/schemas/TourId"
        title:
          type: string
          description: Title of the option.
          example: "From Abu Dhabi: Private Transfer to Dubai"
        description:
          type: string
          description: Description of the option.
        meeting_point:
          type: string
          description: Information about where to meet.
        pick_up:
          type: string
          description: Information about the hotel pickup possibilities.
        drop_off:
          type: string
          description: Information about the drop-off (where the tour ends).
        duration:
          $ref: "../commons/fields.yaml#/components/schemas/Duration"
        duration_unit:
          $ref: "../commons/fields.yaml#/components/schemas/DurationUnit"
        coordinate_type:
          type: string
          description: Information about the type of the coordinates. It defines if the information is exactly enough for the customer to walk / get there.
          enum: [exact, approximate]
        free_sale:
          $ref: "../commons/fields.yaml#/components/schemas/FreeSale"
        cond_language:
          type: object
          properties:
            language_audio:
              type: array
              items:
                $ref: "../commons/fields.yaml#/components/schemas/Language"
              description: List of languages that are available as audio guide
              example: [de, fr, es, ru]
            language_booklet:
              type: array
              items:
                $ref: "../commons/fields.yaml#/components/schemas/Language"
              description: List of languages that are available as booklet
              example: [de, fr, en]
            language_live:
              type: array
              items:
                $ref: "../commons/fields.yaml#/components/schemas/Language"
              description: List of languages that are spoken by the guide
              example: [de, en]
        booking_parameter:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of the booking parameter.
                enum: [language, hotel, comment, supplier_requested_question]
                example: supplier_requested_question
              description:
                type: string
                description: Description of the property.
                example: Please provide the client names, flight details, and pick up and drop-off location.
              mandatory:
                type: boolean
                description: Flag if this parameter / property is mandatory for booking.
                example: true
        services:
          type: object
          properties:
            prt:
              type: boolean
              description: If true, the option is closed after on booking. The customer will be on the tour without any other guests expect those included in the same booking.
              example: true
            stl:
              type: boolean
              description: If true, the customer does not need to wait in line.
              example: true
            wlc:
              type: boolean
              description: If true, there is wheel chair access.
              example: true
        coordinates:
          $ref: "../commons/objects.yaml#/components/schemas/Coordinates"
        price:
          $ref: "../commons/objects.yaml#/components/schemas/StartingPrice"
        special:
          type: object
          properties:
            original_price:
              $ref: "../commons/fields.yaml#/components/schemas/Price"
              description: Original price (without the special offer).
            savings:
              type: number
              description: The discount in percent.
            apps_only:
              type: boolean
              description: Flag if the special offer is only available for the GYG internal mobile apps.

    TourOptionPricing:
      description: Pricings for a tour option
      type: object
      properties:
        pricing_id:
          type: integer
          description: Pricing ID to select the right pricing object for a given time slot. The correct pricing_id is part of the `/options/{option_id}/availabilities` response.
        total_minimum_participants:
          type: integer
          description: Minimal participants needed for every booking.
        total_maximum_participants:
          type: integer
          description: Maximum participants allowed to be booked.
        categories:
          type: object
          description: The pax categories of which this pricing consists of
          properties:
            id:
              type: integer
              description: The Pricing category ID
            name:
              type: string
              description: Translated name of the category.
              example: Adults
            min_age:
              type: integer
              description: The minimum age of a participant such that this price applies.
              example: 21
            max_age:
              type: integer
              description: The maximum age of a participant such that this price applies.
              example: 99
            stand_alone:
              type: boolean
              description: Can this category be booked autonomously? For example an 'Infant' category can most of the times not be booked without another person joining the tour. So the 'Infant' category would have set standAlone to false.
            addon:
              type: boolean
              description: Is this category an addon? An addon is something that can be booked additionally to the tour such as Lunch on a city tour an additional transfer to the meeting point or a child seat for an airport transfer.
            scale:
              type: object
              description: The scales for this pricing category. Depending on the number of bookings you are going to do the price changes.
              properties:
                min_participants:
                  type: integer
                  description: The minimal number of participants needed to apply this scale.
                max_participants:
                  type: integer
                  description: The maximum number of participants needed to apply this scale.
                retail_price:
                  type: number
                  description: The price for which the tour option is sold to the customer.
                net_price:
                  type: number
                  description: The price which needs to be paid to GetYourGuide. The difference between retailPrice and netPrice is the reseller commission.
                type:
                  type: string
                  description: The type of the scale
                  enum:
                    - pax
                    - flat

