openapi: 3.0.2
paths: {}
info:
  title: Payments Schema
  version: 1.0.0
components:
  schemas:
    
    Paypal:
      description: Paypal
      type: object
      properties:
        paypal:
          type: object
          properties:
            return_url: 
              type: string
              example: https://success.example
            cancel_url: 
              type: string
              example: https://failure.example
    
    EncryptedCreditCard:
      description:  EncryptedCreditCard
      type: object
      properties:
        encrypted_credit_card:
          type: object
          properties:
            format: 
              type: string
              example: adyen
            return_url: 
              type: string
              example: https://success.example
            cancel_url: 
              type: string
              example: https://failure.example
            user_agent:
              type: string
              example: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
            data:
              type: string
              description: Encrypted credit card information which is returned from Adyens CSE javascript library
              example: "adyenjs_0_1_19$WeyFKtrch70Ce+uN+4S4" 