openapi: 3.0.2
paths: {}
info:
  title: Payments Schema
  version: 1.0.0
components:
  schemas:
    #Methods
    Paypal:
      description: Paypal
      type: object
      properties:
        paypal:
          type: object
          properties:
            return_url:
              $ref: "#/components/schemas/ReturnUrl"
            cancel_url:
              $ref: "#/components/schemas/CancelUrl"
    EncryptedCreditCard:
      description: EncryptedCreditCard
      type: object
      properties:
        encrypted_credit_card:
          type: object
          properties:
            format:
              type: string
              example: adyen
            return_url:
              $ref: "#/components/schemas/ReturnUrl"
            cancel_url:
              $ref: "#/components/schemas/CancelUrl"
            user_agent:
              type: string
              example: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
            data:
              type: string
              description: Encrypted credit card information which is returned from Adyens CSE javascript library. Please see the public github repo `partner-api-spec` wiki for more details.
              example: "adyenjs_0_1_19$WeyFKtrch70Ce+uN+4S4"

    # Payment objects
    PaymentProcess:
      type: object
      description: Information for 2 step checkout such as PayPal or 3DS Credit Card.
      properties:
        payment_url:
          type: string
          description: Url the customer should be redirected to, to complete the transaction.
          format: uri
          example: "https://www.sandbox.paypal.com/webscr?cmd=_express-checkout&useraction=commit&token=EC-666887694144543663P"
        return_url:
          $ref: "#/components/schemas/ReturnUrl"
        cancel_url:
          $ref: "#/components/schemas/CancelUrl"
    PaymentInfoInPayment:
      properties:
        payment_currency:
          $ref: "#/components/schemas/PaymentCurrency"
        total_price:
          $ref: "#/components/schemas/TotalPrice"
        precoupon_price:
          $ref: "#/components/schemas/PrecouponPrice"
    PaymentInfoConfirmed:
      allOf:
        - $ref: "#/components/schemas/PaymentInfoInPayment"
        - type: object
          properties:
            payment_method:
              $ref: "#/components/schemas/PaymentMethod"
            coupon_info:
              $ref: "#/components/schemas/CouponInfo"
            invoice_reference:
              $ref: "#/components/schemas/InvoiceReference"

    # Data fields for payment objects
    CancelUrl:
      description: Url the customer will be redirected to by the payment provider, after failed completing the transaction.
      type: string
      format: uri
      example: "https://failure.example"
    CouponInfo:
      type: string
      description: The code of the coupon if one was used.
      example: test
    InvoiceReference:
      type: string
      description: The invoice reference number.
      example: GCI-0032724458
    PaymentCurrency:
      type: string
      description: The currency in which the payment has been processed.
      example: EUR
    PaymentMethod:
      type: string
      enum: ["cc", "pp", "dd"]
      description: >
        The payment method used to pay:
          * `cc`: credit card
          * `pp`: PayPal
          * `dd`: direct debit (SEPA, only available in Germany)
      example: cc
    PrecouponPrice:
      $ref: "../commons/fields.yaml#/components/schemas/Price"
    ReturnUrl:
      description: Url the customer will be redirected to by the payment provider, after successful completing the transaction.
      type: string
      format: uri
      example: "https://success.example"
    TotalPrice:
      $ref: "../commons/fields.yaml#/components/schemas/Price"
