openapi: 3.0.2
paths: {}
info:
  title: Payments Schema
  version: 1.0.0
components:
  schemas:
    #Methods
    Paypal:
      description: Paypal
      type: object
      properties:
        paypal:
          type: object
          properties:
            return_url:
              type: string
              example: https://success.example
            cancel_url:
              type: string
              example: https://failure.example
    EncryptedCreditCard:
      description: EncryptedCreditCard
      type: object
      properties:
        encrypted_credit_card:
          type: object
          properties:
            format:
              type: string
              example: adyen
            return_url:
              type: string
              example: https://success.example
            cancel_url:
              type: string
              example: https://failure.example
            user_agent:
              type: string
              example: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
            data:
              type: string
              description: Encrypted credit card information which is returned from Adyens CSE javascript library
              example: "adyenjs_0_1_19$WeyFKtrch70Ce+uN+4S4"

    # Payment objects
    PaymentProcess:
      type: object
      description: Information for 2 step checkout such as PayPal or 3DS Credit Card.
      properties:
        payment_url:
          type: string
          description: Url the customer should be redirected to, to complete the transaction.
          format: uri
          example: "https://www.sandbox.paypal.com/webscr?cmd=_express-checkout&useraction=commit&token=EC-666887694144543663P"
        return_url:
          type: string
          description: Url the customer will be redirected to by the payment provider, after successful completing the transaction.
          format: uri
          example: "https://success.example"
        cancel_url:
          type: string
          description: Url the customer will be redirected to by the payment provider, after failed completing the transaction.
          format: uri
          example: "https://failure.example"
    PaymentInfoInPayment:
      properties:
        payment_currency:
          $ref: "#/components/schemas/PaymentCurrency"
        total_price:
          $ref: "#/components/schemas/TotalPrice"
        precoupon_price:
          $ref: "#/components/schemas/PrecouponPrice"
    PaymentInfoConfirmed:
      type: object
      properties:
        payment_currency:
          $ref: "#/components/schemas/PaymentCurrency"
        total_price:
          $ref: "#/components/schemas/TotalPrice"
        precoupon_price:
          $ref: "#/components/schemas/PrecouponPrice"
        payment_method:
          $ref: "#/components/schemas/PaymentMethod"
        coupon_info:
          $ref: "#/components/schemas/CouponInfo"
        invoice_reference:
          $ref: "#/components/schemas/InvoiceReference"

    # Data fields for payment objects
    PaymentCurrency:
      type: string
      description: The currency in which the payment has been processed.
      example: EUR
    TotalPrice:
      type: number
      description: The total price of the shopping cart.
      example: 209.78
    PrecouponPrice:
      type: number
      description: The price of the shopping cart before coupons have been applied.
      example: 209.78
    PaymentMethod:
      type: string
      enum: ["cc", "pp", "dd"]
      description: >
        The payment method used to pay:
          * `cc`: credit card
          * `pp`: PayPal
          * `dd`: direct debit (SEPA, only available in Germany)
      example: cc
    CouponInfo:
      type: string
      description: The code of the coupon if one was used.
      example: test
    InvoiceReference:
      type: string
      description: The invoice reference number.
      example: GCI-0032724458
