openapi: 3.0.2
paths: {}
info:
  title: Picture Schema
  version: 1.0.0
components:
  schemas:
    Picture:
      description: Picture
      type: object
      properties:
        id:
          type: integer
          description: Picture id.
          example: 66317
        url:
          type: string
          description: The URL string for the image. Important, The [format_id] needs to be replaced by a valid format id. You can find the list of all available IDs in the github wiki.
          example: https://img-getyourguide-com.partner.gygtest.com/img/tour_img-436036-[format_id].jpg
        ssl_url:
          type: string
          description: The URL string for the image. Important, The [format_id] needs to be replaced by a valid format id. You can find the list of all available IDs in the github wiki.
          example: https://img-getyourguide-com.partner.gygtest.com/img/tour_img-436036-[format_id].jpg
        verified:
          type: boolean
          description: Indicates if the image is verified by GetYourGuide
          example: false
