openapi: 3.0.2
paths: {}
info:
  title: Reviews Schema
  version: 1.0.0
components:
  schemas:
    Outline:
      type: array
      items:
        type: object
        properties:
          rating:
            type: integer
            description: The rating for which this outline is. Usually between 1 and 5.
            example: 5
          number_of_reviews:
            type: integer
            description: The number of reviews for this rating.
            example: 0
          share:
            type: number
            description: The percentage of all reviews that have this rating.
            example: 96

    ReviewItems:
      type: array
      items:
        type: object
        properties:
          review_id:
            type: integer
            description: The review ID.
            example: 786101
          tour_id:
            type: integer
            description: The tour ID to which this review belongs to.
            example: 66317
          supplier_id:
            type: integer
            description: The ID of the supplier of the tour referenced by tour ID.
            example: 13587
          review_date:
            type: string
            description: The date and time of when the review was created.
            example: "2017-05-01T13:42:34Z"
          subject:
            type: string
            description: The subject of the review.
            example: Very good
          comment:
            type: string
            description: A comment of the user about the tour.
            example: Super
          reviewer_name:
            type: string
            description: The name of the person who did the review.
            example: Reichenbach – France
          review_rating:
            type: integer
            description: The overall rating of the review. A number between 1 and 5 where 1 is lowest and 5 is highest.
            example: 5
          review_rating_service:
            type: integer
            description: The rating for the service quality. A number between 1 and 5 where 1 is lowest and 5 is highest.
            example: 5
          review_rating_orga:
            type: integer
            description: The rating for the organization of the activity. A number between 1 and 5 where 1 is lowest and 5 is highest.
            example: 5
          review_rating_value:
            type: integer
            description: Value for money rating. A number between 1 and 5 where 1 is lowest and 5 is highest.
            example: 5
          review_rating_safety:
            type: integer
            description: Rating for safety. A number between 1 and 5 where 1 is lowest and 5 is highest.
            example: 5
