openapi: 3.0.2
paths: {}
info:
  title: Supplier Schema
  version: 1.0.0
components:
  schemas:
    Supplier:
      type: object
      properties:
        supplier_id:
          type: integer
          description: Supplier id
          example: 26045
        name:
          type: string
          description: Name of the supplier
          example: GetYourGuide Tours & Tickets GmbH
        email:
          $ref: "../commons/fields.yaml#/components/schemas/Email"
        phone_number:
          $ref: "../commons/fields.yaml#/components/schemas/PhoneNumber"
        description:
          type: string
          description: Description of the supplier
          example: Description of the supplier
        rating:
          $ref: "../commons/fields.yaml#/components/schemas/Rating"
        number_of_reviews:
          type: integer
          description: Overal number of reviews/ratings.
          example: 5
        categories:
          type: array
          description: List of categories in which the supplier offers tours.
          items:
            $ref: "../commons/objects.yaml#/components/schemas/TourCategory"
        logo_url:
          type: string
          format: uri
          description: URL to the logo of the supplier.
          example: https://img-getyourguide-com.partner.gygtest.com/img/profile_picture-26045-1860042995-[format_id].jpg
        address:
          $ref: "../commons/objects.yaml#/components/schemas/Address"
