openapi: 3.0.2
paths: {}
info:
  title: Time-slots Schema
  version: 1.0.0
components:
  schemas:
    TimeSlots:
      description: A list of time-slots including pricing information.
      type: array
      items:
        type: object
        properties:
          tour_id:
            $ref: "../commons/fields.yaml#/components/schemas/TourId"
          option_id:
            $ref: "../commons/fields.yaml#/components/schemas/OptionId"
          bookable_until:
            $ref: "../commons/fields.yaml#/components/schemas/Datetime"
          timezone:
            type: string
            example: "Europe/Lisbon"
          start_time:
            $ref: "../commons/fields.yaml#/components/schemas/Datetime"
          end_time:
            $ref: "../commons/fields.yaml#/components/schemas/Datetime"
          vacancies:
            description: Number of seats that are available for a given time slot.
            type: integer
            example: 99
          max_vacancies:
            description: test
            type: integer
            example: 99
          min_participants:
            type: integer
            description: Minimal participants needed for every booking.
          max_participants:
            type: integer
            description: Maximum participants allowed to be booked.
          from_price:
            type: number
            description: Cheapest price
          pricing_categories:
            type: array
            items:
              type: object
              description: The pax categories of which this pricing consists of
              properties:
                name:
                  type: string
                  description: Translated name of the category.
                  example: Adults
                min_age:
                  type: integer
                  description: The minimum age of a participant such that this price applies.
                  example: 21
                max_age:
                  type: integer
                  description: The maximum age of a participant such that this price applies.
                  example: 99
                independently_bookable:
                  type: boolean
                  description: Can this category be booked autonomously? For example an 'Infant' category can most of the times not be booked without another person joining the tour. So the 'Infant' category would have set standAlone to false.
                addon:
                  type: boolean
                  description: Is this category an addon? An addon is something that can be booked additionally to the tour such as Lunch on a city tour an additional transfer to the meeting point or a child seat for an airport transfer.
                prices:
                  type: array
                  items:
                    type: object
                    description: The scales for this pricing category. Depending on the number of bookings you are going to do the price changes.
                    properties:
                      min_participants:
                        type: integer
                        description: The minimal number of participants needed to apply this scale.
                      max_participants:
                        type: integer
                        description: The maximum number of participants needed to apply this scale.
                      retail_price:
                        type: number
                        description: The price for which the tour option is sold to the customer.
                      net_price:
                        type: number
                        description: The price which needs to be paid to GetYourGuide if discounted net price does not exists. The difference between retailPrice and netPrice is the reseller commission.
                      type:
                        type: string
                        description: The type of the scale
                        enum:
                          - pax
                          - flat
                      deals:
                        type: array
                        items:
                          type: object
                          description: The possible deals for this pricing category, if any.
                          properties:
                            discounted_retail_price:
                              type: number
                              description: The discounted price for which the tour option is sold to the customer.
                            discounted_net_price:
                              type: number
                              description: The price which needs to be paid to GetYourGuide. The difference between retailPrice and netPrice is the reseller commission.
                            percentage:
                              type: number
                              description: The percentage of the discount
                            type:
                              type: string
                              description: |
                                The discount type, possible values:
                                - standard
                                - early_bird
                                - last_minute
                            vacancy_limit:
                              type: integer
