openapi: 3.0.2
info:
  title: Tour Schema
  version: 1.0.0
paths: {}
components:
  schemas:
    Tour:
      description: A tour is a product.
      type: object
      properties:
        tour_id:
          $ref: "../commons/fields.yaml#/components/schemas/TourId"
        tour_code:
          type: string
          description: Tour reference code.
          example: 2-Day
        cond_language:
          type: array
          description: Available conduction languages. List of ISO language codes (ISO 639-1).
          items:
            type: string
            enum: [en, es, fr]
            example: en
        title:
          type: string
          description: Title of the option.
          example: 2-Park 2-Day Universal Orlando™ Theme Park Tickets
        abstract:
          type: string
          description: Short description of the tour.
          example: Universal Orlando Resort is an entire universe of action and thrills with two jaw-dropping theme parks, exceptional shopping and incredible entere unforgettable experiences together. You can have the ultimate adventure, enjoy fun with your kids, rejuvenatainment
        description:
          type: string
          description: Long description of the tour.
          example: At both Universal Studios Florida and Universal's Islands of Adventure ... The ticket must be used by the first use date printed on the ticket. The ticket will expire in full on the expiration date printed on ticket. Unused days shall be forfeited. These tickets are not valid for residents of the UK and Ireland
        is_auto_translation:
          type: boolean
          description: Flag if the title, abstract, description, … are auto-translated.
          example: false
        is_english_fallback:
          type: boolean
          description: Flag if the title, abstract, description, … are English since we don't have the translation yet.
          example: false
        additional_information:
          type: string
          description: Additional information for the customer.
          example: Tickets must be used by the same person on all days...you must present the actual Universal Orlando ticket to receive entry to the parks.
        bestseller:
          type: boolean
          description: Flag if the tour is a bestseller.
          example: false
        certified:
          type: boolean
          description: Flag if the tour is a certified tour.
          example: true
        has_pick_up:
          type: boolean
          description: Indicates if pickup is available for this product
          example: true
        overall_rating:
          type: number
          description: Overall rating of the tour (across all tour options).
          example: 4.96
        number_of_ratings:
          type: number
          description: Number of rating of the tour.
          example: 25
        highlights:
          type: array
          description: List of highlights of that tour.
          items:
            type: string
        inclusions:
          type: string
          description: What's included in the tour.
          example: • Entry to both Universal Studios Florida and Universal’s Islands of Adventure for 2-days
        exclusions:
          type: string
          description: What's not included in the tour.
          example: Parking
        pictures:
          type: array
          items:
            $ref: "./picture.yaml#/components/schemas/Picture"
        coordinates:
          description: Coordinates of the primary location (first entry in the locations array) attributed to the tour. This is usually an area/city the tour is located in and not the actual meeting point. The meeting point for each tour option can be retrieved from /tours/[tour_id]/options.
          $ref: "./coordinates.yaml#/components/schemas/Coordinates"
        price:
          description: Starting price. Should be read as e.g. "from XX.YY USD".
          $ref: "./price.yaml#/components/schemas/Price"
        categories:
          description: List of categories ordered according to importance.
          type: array
          items:
            $ref: "./category.yaml#/components/schemas/Category"
        locations:
          description: List of locations ordered according to importance.
          type: array
          items:
            $ref: "./location.yaml#/components/schemas/Location"
        url:
          type: string
          description: URL of the tour on the GetYourGuide website.
          example: https://www-getyourguide-com.partner.gygtest.com/orlando-l191/walt-disney-world-orlando-with-ticket-options-t50872/?partner_id=173E8&psrc=partner_api¤cy=EUR
        translations:
          type: string
          description: Available translations of the content of this tour. List of ISO language codes (ISO 639-1).
          enum:
            - da
            - de
            - en
            - es
            - fr
            - it
            - nl
            - no
            - pl
            - pt
            - fi
            - sv
            - tr
            - zh
        free_sale:
          type: string
          description: Indicates whether there exists at least one tour option of which the booking engine is free-sale (i.e. whether a booking does not require confirmation by the supplier).
        mobile_voucher:
          type: boolean
          description: If the tour accepts mobile voucher.
          example: true
        supplier_id:
          type: number
          description: The supplier is
          example: 24066
        durations:
          type: array
          items:
            $ref: "./duration.yaml#/components/schemas/Duration"
        cancellation_policy_text:
          $ref: "../commons/fields.yaml#/components/schemas/CancellationPolicyText"
        health_advisory:
          $ref: "#/components/schemas/HealthAdvisory"
        health_requirement:
          $ref: "#/components/schemas/HealthRequirement"
        guide_type:
          type: string
          enum:
            - none
            - host_or_greeter
            - instructor
            - driver
            - live_tour_guide
          description: >
            Type of guide that is conducting the tour, available are
              * `none`: no guide available for this tour.
              * `host_or_greeter`: a host or greeter that welcomes the customer.
              * `instructor`: an instructor e.g. for diving classes.
              * `driver`: a driver for motorized tours.
              * `live_tour_guide`: a standard live tour guide.

    TourOption:
      description: Tour option
      type: object
      properties:
        option_id:
          type: integer
          description: Tour option id (option id).
        tour_id:
          type: integer
          description: Tour id that option belongs to.
        title:
          type: string
          description: Title of the option.
        description:
          type: string
          description: Description of the option.
        pick_up:
          type: string
          description: Information about the hotel pickup possibilities.
        meeting_point:
          type: string
          description: Information about where to meet.
        drop_off:
          type: string
          description: Information about the drop-off (where the tour ends).
        duration:
          type: number
          description: Duration of the tour (to be used in combination with duration unit.
        duration_unit:
          type: string
          description: Unit of the duration field in day, hour or minute.
        coordinate_type:
          type: string
          description: Information about the type of the coordinates. It defines if the information is exactly enough for the customer to walk / get there. = ['exact', 'approximate'].
        free_sale:
          type: boolean
          description: Indicates whether if the tour option's booking engine is free-sale (i.e. whether a booking does not require confirmation by the supplier).
        cond_language:
          type: object
          properties:
            language_audio:
              type: object
              description: List of languages codes (ISO 639-1) that are available as audio guide
            language_booklet:
              type: object
              description: List of languages codes (ISO 639-1) that are available as booklet
            language_live:
              type: object
              description: List of languages codes (ISO 639-1) that are spoken by the guide
        booking_parameter:
          type: object
          properties:
            name:
              type: string
              description: Name of the property = ['language', 'hotel', 'comment', 'supplier_requested_question'].
            value_1:
              type: string
              description: First / Primary value of the property.
            value_2:
              type: string
              description: Some property require a second value.
            description:
              type: string
              description: Description of the property.
            mandatory:
              type: boolean
              description: Flag if this parameter / property is mandatory for booking.
        services:
          type: object
          properties:
            prt:
              type: boolean
              description: If true, the option is closed after on booking. The customer will be on the tour without any other guests expect those included in the same booking.
            stl:
              type: boolean
              description: If true, the customer does not need to wait in line.
            wlc:
              type: boolean
              description: If true, there is wheel chair access.
        coordinates:
          $ref: "./coordinates.yaml#/components/schemas/Coordinates"
        price:
          $ref: "./price.yaml#/components/schemas/Price"
          values:
            type: object
            properties:
              amount:
                type: number
                description: Price for the adult fare of the cheapest option in the requested currency.
              special:
                type: array
                description: Special offer.
        special:
          type: object
          properties:
            original_price:
              type: number
              description: Original price (without the special offer).
            savings:
              type: number
              description: The discount in percent.
            apps_only:
              type: boolean
              description: Flag if the special offer is only available for the GYG internal mobile apps.

    TourOptionPricing:
      description: Pricings for a tour option
      type: object
      properties:
        pricing_id:
          type: integer
          description: Pricing ID
        total_minimum_participants:
          type: integer
          description: Minimal participants needed for every booking.
        total_maximum_participants:
          type: integer
          description: Maximum participants allowed to be booked.
        categories:
          type: object
          description: The categories of which this pricing consists of
          properties:
            id:
              type: integer
              description: The Pricing category ID
            name:
              type: string
              description: Translated name of the category. Example values are 'Adult', 'Child' or 'Infant'
            min_age:
              type: integer
              description: The minimum age of a participant such that this price applies
            max_age:
              type: integer
              description: The maximum age of a participant such that this price applies
            stand_alone:
              type: boolean
              description: Can this category be booked autonomously? For example an 'Infant' category can most of the times not be booked without another person joining the tour. So the 'Infant' category would have set standAlone to false.
            addon:
              type: boolean
              description: Is this category an addon? An addon is something that can be booked additionally to the tour such as Lunch on a city tour an additional transfer to the meeting point or a child seat for an airport transfer.
            scale:
              type: object
              description: The scales for this pricing category. Depending on the number of bookings you are going to do the price changes.
              properties:
                min_participants:
                  type: integer
                  description: The minimal number of participants needed to apply this scale.
                max_participants:
                  type: integer
                  description: The maximum number of participants needed to apply this scale.
                retail_price:
                  type: number
                  description: The price for which the tour option is sold to the customer.
                net_price:
                  type: number
                  description: The price which needs to be paid to GetYourGuide. The difference between retailPrice and netPrice is the reseller commission.
                type:
                  type: string
                  description: The type of the scale
                  enum:
                    - pax
                    - flat

    TourOptionAvailability:
      type: object
      properties:
        start_time:
          type: string
          description: Start Time and Date in local time.
          example: 2017-09-01T09:00:00
        end_time:
          type: string
          description: Optional response parameter. End Time of a Tour - only given in case of opening hours.
          example: 2017-09-01T09:00:00
        pricing_id:
          type: integer
          description: The price id for this particular availability
        vacancies:
          type: integer
          description: Number of seats that are available.
        discount:
          type: integer
          description: If the starting time is eligible for a deal, specify the discount on the retail_price of the corresponding pricing_id.

    HealthAdvisory:
      type: array
      items:
        type: object
        properties:
          tag_id:
            type: number
            description: Tag Id
            example: 161578
          name:
            type: string
            description: Tag name
            example: Frequent_cleaning
          text:
            type: string
            description: Verbose description
            example: All areas that customers touch are frequently cleaned

    HealthRequirement:
      type: array
      items:
        type: object
        properties:
          tag_id:
            type: number
            description: Tag Id
            example: 161578
          name:
            type: string
            description: Tag name
            example: Mask_required
          text:
            type: string
            description: Verbose description
            example: You are required to bring and wear a mask
