openapi: 3.0.2
info:
  title: Tour Schema
  version: 1.0.0
paths: {}
components:
  schemas:
    Tour:
      description: A tour is a product.
      type: object
      properties:
        tour_id:
          $ref: "../commons/fields.yaml#/components/schemas/TourId"
        tour_code:
          type: string
          description: Tour reference code.
          example: 2-Day
        cond_language:
          type: array
          description: Available conduction languages.
          items:
            $ref: "../commons/fields.yaml#/components/schemas/Language"
          example: [en, de, es]
        title:
          type: string
          description: Title of the option.
          example: 2-Park 2-Day Universal Orlando™ Theme Park Tickets
        abstract:
          type: string
          description: Short description of the tour.
          example: Universal Orlando Resort is an entire universe of action and thrills with two jaw-dropping theme parks, exceptional shopping and incredible entere unforgettable experiences together. You can have the ultimate adventure, enjoy fun with your kids, rejuvenatainment
        description:
          type: string
          description: Long description of the tour.
          example: At both Universal Studios Florida and Universal's Islands of Adventure ... The ticket must be used by the first use date printed on the ticket. The ticket will expire in full on the expiration date printed on ticket. Unused days shall be forfeited. These tickets are not valid for residents of the UK and Ireland
        is_auto_translation:
          type: boolean
          description: Flag if the title, abstract, description, … are auto-translated.
          example: false
        is_english_fallback:
          type: boolean
          description: Flag if the title, abstract, description, … are English since we don't have the translation yet.
          example: false
        additional_information:
          type: string
          description: Additional information for the customer.
          example: Tickets must be used by the same person on all days...you must present the actual Universal Orlando ticket to receive entry to the parks.
        bestseller:
          type: boolean
          description: Flag if the tour is a bestseller.
          example: false
        certified:
          type: boolean
          description: Flag if the tour is a certified tour.
          example: true
        has_pick_up:
          type: boolean
          description: Indicates if pickup is available for this product
          example: true
        overall_rating:
          $ref: "../commons/fields.yaml#/components/schemas/Rating"
        number_of_ratings:
          type: number
          description: Number of rating of the tour.
          example: 25
        highlights:
          type: array
          description: List of highlights of that tour.
          items:
            type: string
        inclusions:
          type: string
          description: What's included in the tour.
          example: • Entry to both Universal Studios Florida and Universal’s Islands of Adventure for 2-days
        exclusions:
          type: string
          description: What's not included in the tour.
          example: Parking
        pictures:
          type: array
          items:
            $ref: "./picture.yaml#/components/schemas/Picture"
        coordinates:
          $ref: "../commons/objects.yaml#/components/schemas/Coordinates"
        price:
          $ref: "../commons/objects.yaml#/components/schemas/StartingPrice"
        categories:
          description: List of categories ordered according to importance.
          type: array
          items:
            $ref: "../commons/objects.yaml#/components/schemas/TourCategory"
        locations:
          description: List of locations ordered according to importance.
          type: array
          items:
            $ref: "./location.yaml#/components/schemas/Location"
        url:
          type: string
          format: uri
          description: URL of the tour on the GetYourGuide website.
          example: https://www-getyourguide-com.partner.gygtest.com/orlando-l191/walt-disney-world-orlando-with-ticket-options-t50872/?partner_id=173E8&psrc=partner_api¤cy=EUR
        translations:
          $ref: "../commons/fields.yaml#/components/schemas/Language"
        free_sale:
          type: boolean
          description: Indicates whether there exists at least one tour option of which the booking engine is free-sale (i.e. whether a booking does not require confirmation by the supplier).
        mobile_voucher:
          type: boolean
          description: If the tour accepts mobile voucher.
          example: true
        supplier_id:
          $ref: "../commons/fields.yaml#/components/schemas/SupplierId"
        durations:
          type: array
          items:
            $ref: "../commons/objects.yaml#/components/schemas/Durations"
        cancellation_policy_text:
          $ref: "../commons/fields.yaml#/components/schemas/CancellationPolicyText"
        health_advisory:
          $ref: "#/components/schemas/HealthAdvisory"
        health_requirement:
          $ref: "#/components/schemas/HealthRequirement"
        guide_type:
          type: string
          enum:
            - none
            - host_or_greeter
            - instructor
            - driver
            - live_tour_guide
          description: >
            Type of guide that is conducting the tour, available are
              * `none`: no guide available for this tour.
              * `host_or_greeter`: a host or greeter that welcomes the customer.
              * `instructor`: an instructor e.g. for diving classes.
              * `driver`: a driver for motorized tours.
              * `live_tour_guide`: a standard live tour guide.

    HealthAdvisory:
      type: array
      items:
        type: object
        properties:
          tag_id:
            type: number
            description: Tag Id
            example: 161578
          name:
            type: string
            description: Tag name
            example: Frequent_cleaning
          text:
            type: string
            description: Verbose description
            example: All areas that customers touch are frequently cleaned

    HealthRequirement:
      type: array
      items:
        type: object
        properties:
          tag_id:
            type: number
            description: Tag Id
            example: 161578
          name:
            type: string
            description: Tag name
            example: Mask_required
          text:
            type: string
            description: Verbose description
            example: You are required to bring and wear a mask
