openapi: 3.0.0

info:
  title: Partner Api
  description: This GetYourGuide Partner API provides access to GetYourGuide’s marketplace for tours and activities. It has a RESTful interface and uses the JSON media format. Access is secured via SSL and an API access token.
  version: 1.0.0
  contact:
    name: Partner Tech
    url: https://partner.getyourguide.com.com/

servers:
  - url: https://api.getyourguide.com/1
    description: Production
  - url: https://api.testing1.gygtest.com/1
    description: Testing

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-ACCESS-TOKEN

security:
  - ApiKeyAuth: []

paths:
  # Configuration
  /configuration/{version}:
    $ref: 'paths/configuration.yaml#/paths/~1configuration~1{version}'
  /configuration/payment:
    $ref: 'paths/configuration.yaml#/paths/~1configuration~1payment'
  # Bookings
  /bookings:
    $ref: 'paths/bookings.yaml#/paths/~1bookings'
  /bookings/{booking_hash}:
    $ref: 'paths/bookings.yaml#/paths/~1bookings~1{booking_hash}'
  # Carts
  /carts:
    $ref: 'paths/carts.yaml#/paths/~1carts'
  /carts/{shopping_cart_hash}:
    $ref: 'paths/carts.yaml#/paths/~1carts~1{shopping_cart_hash}'
  # Categories
  /categories:
    $ref: 'paths/categories.yaml#/paths/~1categories'
  /categories/{category_id}:
    $ref: 'paths/categories.yaml#/paths/~1categories~1{category_id}'
  # Options
  /options/{option_id}:
    $ref: 'paths/options.yaml#/paths/~1options~1{option_id}'



  # Tours
  /tours:
    $ref: 'paths/tours.yaml#/paths/~1tours'
  # Bulk Downloads
  /bulk_tours:
    $ref: 'paths/bulk.yaml#/paths/~1bulk_tours'
  /bulk_availabilities:
    $ref: 'paths/bulk.yaml#/paths/~1bulk_availabilities'
