openapi: 3.0.0

info:
  title: Partner Api
  description: This GetYourGuide Partner API provides access to GetYourGuide’s marketplace for tours and activities. It has a RESTful interface and uses the JSON media format. Access is secured via SSL and an API access token.
  version: 1.0.0
  contact:
    name: Partner Tech
    url: https://partner.getyourguide.com/

externalDocs:
  description: API Wiki
  url: https://github.com/getyourguide/partner-api-spec/wiki/General-Information

servers:
  - url: https://api.getyourguide.com/1
    description: Production
  - url: https://api.testing1.gygtest.com/1
    description: Testing

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-ACCESS-TOKEN

security:
  - ApiKeyAuth: []

paths:
  # Configuration
  /configuration/{version}:
    $ref: 'paths/configuration.yaml#/paths/~1configuration~1{version}'
  /configuration/payment:
    $ref: 'paths/configuration.yaml#/paths/~1configuration~1payment'
  /configuration/privileges:
    $ref: 'paths/configuration.yaml#/paths/~1configuration~1privileges'
  # Bookings
  /bookings:
    $ref: 'paths/bookings.yaml#/paths/~1bookings'
  /bookings/{booking_hash}:
    $ref: 'paths/bookings.yaml#/paths/~1bookings~1{booking_hash}'
  # Carts
  /carts:
    $ref: 'paths/carts.yaml#/paths/~1carts'
  /carts/{shopping_cart_hash}:
    $ref: 'paths/carts.yaml#/paths/~1carts~1{shopping_cart_hash}'
  # Categories
  /categories:
    $ref: 'paths/categories.yaml#/paths/~1categories'
  /categories/{category_id}:
    $ref: 'paths/categories.yaml#/paths/~1categories~1{category_id}'
  # Options
  /options/{option_id}:
    $ref: 'paths/options.yaml#/paths/~1options~1{option_id}'
  /options/{option_id}/pricings:
    $ref: 'paths/options.yaml#/paths/~1options~1{option_id}~1pricings'
  /options/{option_id}/availabilities:
    $ref: 'paths/options.yaml#/paths/~1options~1{option_id}~1availabilities'
  # Reviews
  /reviews/tour/{tour_id}:
    $ref: 'paths/reviews.yaml#/paths/~1reviews~1tour~1{tour_id}'
  # Suppliers
  /suppliers/{supplier_id}:
    $ref: 'paths/suppliers.yaml#/paths/~1suppliers~1{supplier_id}'
  # Tours
  /tours:
    $ref: 'paths/tours.yaml#/paths/~1tours'
  /tours/{tour_id}:
    $ref: 'paths/tours.yaml#/paths/~1tours~1{tour_id}'
  /tours/{tour_id}/availabilities:
    $ref: 'paths/tours.yaml#/paths/~1tours~1{tour_id}~1availabilities'
  /tours/{tour_id}/options:
    $ref: 'paths/tours.yaml#/paths/~1tours~1{tour_id}~1options'
  # Bulk Downloads
  /bulk_tours:
    $ref: 'paths/bulk.yaml#/paths/~1bulk_tours'
  /bulk_availabilities:
    $ref: 'paths/bulk.yaml#/paths/~1bulk_availabilities'
