openapi: 3.0.0
info:
  title: Partner Api
  description: GetYourGuide Partner Api
  version: 1.0.0
  contact:
    name: Partner Tech
    url: https://partner.getyourguide.com.com/
servers:
  - url: https://api.getyourguide.com/1
    description: Production
  - url: https://api.testing1.gygtest.com/1
    description: Testing
paths:
  # Configuration
  /configuration/{version}:
    $ref: 'paths/configuration.yaml#/paths/~1configuration~1{version}'
  /configuration/payment:
    $ref: 'paths/configuration.yaml#/paths/~1configuration~1payment'
  # Bookings
  /bookings:
    $ref: 'paths/bookings.yaml#/paths/~1bookings'
  /bookings/{booking_hash}:
    $ref: 'paths/bookings.yaml#/paths/~1bookings~1{booking_hash}'
  # Carts
  /carts:
    $ref: 'paths/carts.yaml#/paths/~1carts'
  /carts/{shopping_cart_hash}:
    $ref: 'paths/carts.yaml#/paths/~1carts~1{shopping_cart_hash}'
  # Tours
  /tours:
    $ref: 'paths/tours.yaml#/paths/~1tours'