openapi: 3.0.2
info:
  title: bookings
  version: 1.0.0
paths: {}
components:
  schemas:
    BookingCreateRequest:
      type: object
      properties:
        base_data:
          type: object
          properties:
            cnt_language:
              description: ISO 639, Language of the text content.
              type: string
              example: "en"
            currency:
              description: ISO 4217, The currency with which you would like to pay.
              type: string
              example: "EUR"
        data:
          type: object
          properties:
            booking:
              type: object
              properties:
                bookable:
                  type: object
                  properties:
                    option_id:
                      $ref: './commons.yaml#/components/schemas/OptionId'
                    datetime:
                      $ref: './commons.yaml#/components/schemas/Datetime'
                    price:
                      type: string
                      example: '170.00'
                    categories:
                      type: array
                      items:
                        type: object
                        properties:
                          category_id:
                            type: string
                            example: '2077534'
                          number_of_participants:
                            type: string
                            example: '5'
                    booking_parameters:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: language
                          value_1:
                            type: string
                            example: language_live
                          value_2:
                            type: string
                            example: en

    BookingCreateResponse:
      type: object
      properties:
        bookings:
          type: object
          properties:
            shopping_cart_id:
              $ref: './commons.yaml#/components/schemas/ShoppingCartId'
            shopping_cart_hash:
              $ref: './commons.yaml#/components/schemas/ShoppingCartHash'
            booking_id:
              $ref: './commons.yaml#/components/schemas/BookingId'
            booking_hash:
              $ref: './commons.yaml#/components/schemas/BookingHash'
            booking_status:
              $ref: './commons.yaml#/components/schemas/BookingStatus'
            return_code:
              description: The return code of the booking service..
              type: number
              example: 0
    
    BookingsGetByHashResponse:
      type: object
      properties:
        bookings:
          type: object
          properties:
            booking_id:
              $ref: './commons.yaml#/components/schemas/BookingId'
            booking_hash:
              $ref: './commons.yaml#/components/schemas/BookingHash'
            booking_status:
              $ref: './commons.yaml#/components/schemas/BookingStatus'
            shopping_cart_id:
              $ref: './commons.yaml#/components/schemas/ShoppingCartId'
            shopping_cart_hash:
              $ref: './commons.yaml#/components/schemas/ShoppingCartHash'
            bookable:
              type: object
              properties:
                tour_id:
                  $ref: './commons.yaml#/components/schemas/TourId'
                option_id:
                  $ref: './commons.yaml#/components/schemas/OptionId'
                datetime:
                  $ref: './commons.yaml#/components/schemas/Datetime'
                datetime_utc:
                  $ref: './commons.yaml#/components/schemas/DatetimeUTC'
                datetime_type:
                  $ref: './commons.yaml#/components/schemas/DatetimeType'
            opening_hours:
              type: array
              items:
                type: object
                properties:
                  opening_time:
                    $ref: './commons.yaml#/components/schemas/Datetime'
                  closing_time:
                    $ref: './commons.yaml#/components/schemas/Datetime'
            price:
              $ref: './commons.yaml#/components/schemas/Price'