openapi: 3.0.2
paths: {}
info:
  title: Common components
  version: 1.0.0
components:
  parameters:
    version:
      name: version
      description: The version of the API of which you want to get the configuration.
      in: path
      required: true
      schema:
        type: string
    bookingHash:
      name: booking_hash
      description: Booking hash
      required: true
      in: path
      schema:
        type: string
    shoppingCartHash:
      name: shopping_cart_hash
      description: The hash of the shopping cart.
      required: true
      in: path
      schema:
        type: string
    cntLanguage:
      name: cnt_language
      description: ISO 639, Language of the text content.
      in: query
      required: true
      schema:
        type: string
        enum:
          - da
          - de
          - en
          - es
          - fr
          - it
          - nl
          - no
          - pl
          - pt
          - fi
          - sv
          - tr
          - zh
    currency:
      name: currency
      description: ISO 4217, The currency with which you would like to pay.
      in: query
      required: true
      schema:
        type: string
        enum:
          - USD
          - EUR
          - AUD
          - GBP
          - CAD
          - DKK
          - NZD
          - NOK
          - PLN
          - SGD
          - SEK
          - CHF
          - AED
    country:
      name: country
      description: ISO 3166-1, The country where to payment originates. Should be the same value as the country_code field of the Billing Address Object.
      in: query
      required: true
      schema:
        type: string
    externalReferenceId:
      name: external_reference_id
      description: The external reference ID. The reseller can supply a reference number under which this booking is referenced in his system. This field contains that number. Maximum length is 255.
      required: false
      in: query
      schema:
        type: string
    categoryId:
      name: category_id
      description: The id of the category
      required: true
      in: path
      schema:
        type: integer
    optionId:
      name: option_id
      description: The ID of the option.
      required: true
      in: path
      schema:
        type: integer
    limit:
      name: Limit
      in: query
      required: false
      description: Number of items to retrieve.
      schema:
        type: integer
        minimum: 1
        maximum: 500
        default: 10
    offset:
      name: Offset
      in: query
      required: false
      description: Offset the list of returned results by this amount.
      schema:
        type: integer
        default: 0
  schemas:
    ShoppingCartId:
      description: The ID of the shopping cart.
      type: number
      example: 32724458
    ShoppingCartHash:
      description: The hash of the shopping cart.
      type: string
      example: '0ESFMXPUANBNSGAOSLR4JWCOD7S4P18K'
    BookingId:
      description: The id of the booking.
      type: number
      example: 13822240
    BookingHash:
      description: The hash of the booking. This identifies the booking.
      type: string
      example: 'WTLDAJ2S335O539FV3YCGZ0JMOCSTB5M'
    BookingStatus:
      description: The status of the booking.
      type: string
      enum: [temp, unconfirmed, confirmed, deleted, canceled, deleted_by_customer, deleted_by_daemon]
      example: 'temp'
    CategoryId:
      description: ID of the category.
      type: integer
      example: 33
    ReturnCode:
      description: The return code of the booking service.
      type: number
      example: 0
    TourId:
      description: The ID of the tour.
      type: number
      example: 50872
    OptionId:
      description: The ID of the tour option.
      type: number
      example: 69232
    Datetime:
      type: string
      example: "2017-09-01T00:00:00"
    DatetimeUTC:
      description: The datetime in UTC of when the activity dates place.
      type: string
      example: "2017-09-01T04:00:00Z"
    DatetimeType:
      description: Is the datetime a date or a datetime. This is needed as some activities only have a day on which they take place.
      type: string
      enum: [date, datetime]
      example: 'date'
    Price:
      description: The price of the activity described in this bookable. You will have to calculate reduced prices yourself. The discount as a percentage value, if present, is retrieved from the options/availabilities endpoint.
      type: number
      format: double
      example: 270
    CancellationPolicyText:
      description: Cancellation policy
      type: string
      example: Your activity is non-refundable,
    CurrentlyCancellableAtNoFee:
      description: Indicates whether this booking is currently cancellable at no fee.
      type: boolean
      example: true
    BookingParameters:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            description: Name of the property
            enum: [language, hotel, comment, supplier_requested_question]
            example: language
          value_1:
            type: string
            description: First / Primary value of the property
            example: language_live
          value_2:
            type: string
            description: The language property requires a second value (e.g. value_1 = language_live, value_2 = en).
            example: en
          mandatory:
            type: boolean
            description: The mandatory booking parameters can be retrieved from the options endpoint
            example: false
    Category:
      description: Tour category
      type: object
      properties:
        category_id:
          type: integer
          description: Category ID
          example: 1
        name:
          type: string
          description: name
          example: Sightseeing Tours
        number_of_tours:
          type: integer
          description: Number of tours
          example: 20
        parent_id:
          type: integer
          description: Parent Category ID
          example: 2
      required:
        - category_id
        - name
        - number_of_tours