openapi: 3.0.2
info:
  title: Common components
  version: 1.0.0
components:

  parameters:

    version:
      name: version
      description: The version of the API of which you want to get the configuration.
      in: path
      required: true
      schema:
        type: string
    bookingHash:
      name: booking_hash
      description: Booking hash
      required: true
      in: path
      schema:
        type: string
    
    cntLanguage:
      name: cnt_language
      description: ISO 639, Language of the text content.
      in: query
      required: true
      schema:
        type: string
    currency:
      name: currency
      description: ISO 4217, The currency with which you would like to pay.
      in: query
      required: true
      schema:
        type: string
    country:
      name: country
      description: ISO 3166-1, The country where to payment originates. Should be the same value as the country_code field of the Billing Address Object.
      in: query
      required: true
      schema:
        type: string
    externalReferenceId:
      name: external_reference_id
      description: The external reference ID. The reseller can supply a reference number under which this booking is referenced in his system. This field contains that number. Maximum length is 255.
      required: false
      in: query
      schema:
        type: string

  schemas:
    ShoppingCartId:
      name: shopping_cart_id
      description: The ID of the shopping cart.
      type: number
      example: 32724458
    ShoppingCartHash:
      description: The hash of the shopping cart.
      type: string
      example: '0ESFMXPUANBNSGAOSLR4JWCOD7S4P18K'
    BookingId:
      description: The id of the booking.
      type: number
      example: 13822240
    BookingHash:
      description: The hash of the booking. This identifies the booking.
      type: string
      example: 'WTLDAJ2S335O539FV3YCGZ0JMOCSTB5M'
    BookingStatus:
      description: The status of the booking.
      type: string
      enum: [temp, unconfirmed, confirmed, deleted, canceled]
      example: 'temp'
    TourId:
      name: tour_id
      description: The ID of the tour.
      type: number
      example: 50872
    OptionId:
      name: option_id
      description: The ID of the tour option.
      type: number
      example: 69232
    Datetime:
      name: datetime
      type: string
      example: "2017-09-01T00:00:00"
    DatetimeUTC:
      name: datetime_utc
      description: The datetime in UTC of when the activity dates place.
      type: string
      example: "2017-09-01T04:00:00Z"
    DatetimeType:
      name: datetime_type
      description: Is the datetime a date or a datetime. This is needed as some activities only have a day on which they take place.
      type: string
      enum: [date, datetime]
      example: 'date'
    Price:
      name: price
      description: The price of the activity described in this bookable. You will have to calculate reduced prices yourself. The discount as a percentage value, if present, is retrieved from the options/availabilities endpoint.
      type: number
      format: double
      example: 270