openapi: 3.0.2
info:
  title: tours
  version: 1.0.0
paths: {}
components:
  schemas:

    ToursQueryResponse:
      type: object
      properties:
        tours:
          type: array
          items:
            $ref: './schema/tour.yaml#/components/schemas/Tour'