openapi: 3.0.2
info:
  title: Common data objects
  version: 1.0.0
paths: { }
components:
  schemas:
    Address:
      type: object
      description: The structured address of the supplier.
      properties:
        street:
          $ref: "fields.yaml#/components/schemas/Street"
        zipCode:
          $ref: "fields.yaml#/components/schemas/ZipCode"
        country:
          $ref: "fields.yaml#/components/schemas/CountryVerbose"
        city:
          $ref: "fields.yaml#/components/schemas/City"
        state:
          $ref: "fields.yaml#/components/schemas/State"
    Coordinates:
      type: object
      required:
        - lat
        - long
      properties:
        lat:
          $ref: "fields.yaml#/components/schemas/Latitude"
        long:
          $ref: "fields.yaml#/components/schemas/Longitude"
    Durations:
      type: object
      properties:
        duration:
          $ref: "fields.yaml#/components/schemas/Duration"
        unit:
          $ref: "fields.yaml#/components/schemas/DurationUnit"
    Special:
      type: object
      properties:
        original_price:
          $ref: "../commons/fields.yaml#/components/schemas/PriceField"
        savings:
          type: number
          description: The maximum possible discount in percent.
          example: 12.0
        apps_only:
          type: boolean
          description: Flag if the special offer is only available for the GYG internal mobile apps.
    StartingPrice:
      type: object
      description: Starting price. Should be read as e.g. "from XX.YY USD.
      properties:
        values:
          type: object
          properties:
            amount:
              $ref: "fields.yaml#/components/schemas/PriceField"
        description:
          type: string
          description: Additional information about the pricing. E.g. 'per group' or 'per person' or 'per Group up to 10 people'.
          example: individual
    StartingPriceDiscounted:
      type: object
      description: Starting price and theoretic maximum possible discount. Should be read as e.g. "from XX.YY USD. The discounts are still bound to individual dates.
      properties:
        values:
          type: object
          properties:
            amount:
              $ref: "fields.yaml#/components/schemas/PriceField"
            special:
              $ref: "#/components/schemas/Special"
        description:
          type: string
          description: Additional information about the pricing. E.g. 'per group' or 'per person' or 'per Group up to 10 people'.
          example: individual
    Viewport:
      description: Describes a rectangular map frame by defining its lower left (SW) and upper right (NE) corners.
      type: object
      properties:
        sw_lat:
          $ref: "fields.yaml#/components/schemas/Latitude"
        sw_long:
          $ref: "fields.yaml#/components/schemas/Longitude"
        ne_lat:
          $ref: "fields.yaml#/components/schemas/Latitude"
        ne_long:
          $ref: "fields.yaml#/components/schemas/Longitude"
    TourCategory:
      type: object
      properties:
        category_id:
          $ref: "fields.yaml#/components/schemas/CategoryId"
        name:
          type: string
          description: Name of the category.
          example: Theme Parks & Amusement Parks
        parent_id:
          $ref: "fields.yaml#/components/schemas/CategoryId"
        number_of_tours:
          type: integer
          description: Number of available tours in the category.
          example: 10
    IntegerRange:
      type: object
      properties:
        min:
          type: integer
          description: Minimum value of the range.
          example: 1
        max:
          type: integer
          description: Maximum value of the range.
          example: 20
    ParticipantCategory:
      type: object
      required:
        - ticket_category
        - name
      properties:
        ticket_category:
          type: string
          example: adult
          description: |
            Possible values:
            - infant
            - child
            - youth
            - student
            - eu_citizen_student
            - adult
            - eu_citizen
            - military
            - senior
            - group
        name:
          type: string
          example: Adults
        age_range:
          $ref: "#/components/schemas/IntegerRange"
        independently_bookable:
          description: Only relevant for non-group categories
          type: boolean
          example: true
    AvailableAddon:
      type: object
      required:
        - id
        - name
        - max_quantity
      properties:
        id:
          type: integer
          example: 1934
        name:
          type: string
          example: "Free drinks"
        max_quantity:
          type: integer
          example: 10
    AvailableDate:
      type: object
      required:
        - date
        - has_deal
      properties:
        date:
          type: string
          format: date
        has_deal:
          description: Flag that indicates whether there is a special offer for this date.
          type: boolean
          example: true
    OpeningHours:
      description: The opening hours of a given attraction or venue in local time.
      type: object
      properties:
        opening_time:
          $ref: "fields.yaml#/components/schemas/Datetime"
        closing_time:
          $ref: "fields.yaml#/components/schemas/Datetime"
    PickUpLocation:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          description: |
            Indicates the source type for pickup. Possible values:
            - from_areas
            - from_locations
        description:
          description: Description of the pick up location translated to the language of the user.
          example: "Pick up from your hotel in Manhattan"
          type: string
        areas:
          type: array
          description: "Provide this if type is 'from_areas'."
          items:
            $ref: "../commons/objects.yaml#/components/schemas/LogisticsArea"
        locations:
          type: array
          description: "Provide this if type is 'from_locations'."
          items:
            $ref: "../commons/objects.yaml#/components/schemas/LogisticsLocation"
        transportation_types:
          type: array
          items:
            $ref: "../commons/objects.yaml#/components/schemas/TransportationType"
    TransportationType:
      type: object
      required: [mode]
      properties:
        mode:
          type: string
          description: |
            Possible values:
            - bicycle
            - mountain_bike
            - electric_bicycle
            - motorcycle
            - scooter
            - segway
            - car
            - limousine
            - jeep_suv
            - van
            - quad_atv
            - bus_coach
            - electric_car
            - vintage_car
            - black_cab
            - sailboat
            - ferry
            - gondola
            - duck_boat
            - jet_ski
            - sightseeing_cruise
            - water_taxi
            - river_boat
            - kayak
            - raft
            - catamaran
            - speed_boat
            - yacht
            - canoe
            - stand_up_paddle_board
            - surfboard
            - submarine
            - other_water_transport
            - train
            - tram
            - helicopter
            - airplane
            - balloon
            - glider
            - cable_car
            - pedicab_rickshaw
            - horse_carriage
            - camel
            - snowmobile
            - sled
            - other_animal
            - public
            - glass_bottom_boat
            - lake_cruise
            - banana_boat
            - beer_boat
            - air_boat
            - dhow
            - subway
            - beer_bike
            - trike
            - tuk_tuk
            - golf_cart
            - motorized_tuk_tuk
            - on_foot
            - horse
            - trolley
    LogisticsArea:
      type: object
      required:
        - name
        - full_address
        - bounding_box
        - coordinates
      properties:
        name:
          type: string
          description: Name of the area. Shorter than full_address e.g. "Manhattan".
        full_address:
          type: string
          description: Representing the area for the pick up location e.g. "Manhattan, New York, USA".
        bounding_box:
          $ref: "../commons/objects.yaml#/components/schemas/BoundingBox"
        coordinates:
          $ref: "../commons/objects.yaml#/components/schemas/Coordinates"
    LogisticsLocation:
      type: object
      required:
        - name
        - full_address
        - bounding_box
        - coordinates
      properties:
        name:
          type: string
          description: Name of the location. Shorter than full_address e.g. Louvre Museum.
        full_address:
          type: string
          description: Representing the location for the pick up location e.g. Louvre Museum, Paris, France.
        coordinates:
          $ref: "../commons/objects.yaml#/components/schemas/Coordinates"
    BoundingBox:
      type: object
      properties:
        sw_lat:
          type: number
          format: double
        sw_long:
          type: number
          format: double
        ne_lat:
          type: number
          format: double
        ne_long:
          type: number
          format: double


