openapi: 3.0.2
info:
  title: Common path parameters
  version: 1.0.0
paths: {}
components:
  parameters:
    bookingHash:
      in: path
      name: booking_hash
      required: true
      schema:
        $ref: ./fields.yaml#/components/schemas/BookingHash
    categoryId:
      in: path
      name: category_id
      required: true
      schema:
        $ref: ./fields.yaml#/components/schemas/CategoryId
    optionId:
      in: path
      name: option_id
      required: true
      schema:
        $ref: ./fields.yaml#/components/schemas/OptionId
    shoppingCartHash:
      in: path
      name: shopping_cart_hash
      required: true
      schema:
        $ref: ./fields.yaml#/components/schemas/ShoppingCartHash
    supplierId:
      description: The supplier id
      in: path
      name: supplier_id
      required: true
      schema:
        type: integer
    tourId:
      description: The tour id
      in: path
      name: tour_id
      required: true
      schema:
        type: integer
    version:
      description: The version of the API of which you want to get the configuration.
      in: path
      name: version
      required: true
      schema:
        type: string
