openapi: 3.0.0
info:
  title: Paths for bookings
  version: 1.0.0
paths:
  /bookings:
    post:
      operationId: BookingsCreate
      description: A booking request can create a shopping cart or add to an existing shopping cart. Either coupon or bookable should be sent in the body of the request
      summary: Create a new booking.
      tags:
        - Bookings
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/externalReferenceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '../components/schema/bookings.yaml#/components/schemas/BookingCreateActivity'
                - $ref: '../components/schema/bookings.yaml#/components/schemas/BookingCreateCoupon'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      bookings:
                        $ref: '../components/schema/bookings.yaml#/components/schemas/BookingCreateResponse'
        400:
          description: Missing Parameters
        500:
          description: Server error

  /bookings/{booking_hash}:
    get:
      operationId: BookingsGetByHash
      summary: Get information about a booking
      tags:
        - Bookings
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/bookingHash'
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '../components/schema/bookings.yaml#/components/schemas/BookingsGetByHashResponse'
        400:
          description: Missing Parameters
        500:
          description: Server error
    delete:
      operationId: bookingsDeleteByHash
      summary: Delete (Cancel) a booking.
      tags:
        - Bookings
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '../components/schema/bookings.yaml#/components/schemas/BookingDeleteResponse'
        400:
          description: Missing Parameters
        500:
          description: Server error