openapi: 3.0.2
info:
  title: Paths for bookings
  version: 1.0.0
paths:
  /bookings:
    post:
      operationId: BookingsCreate
      description: A booking request can create a shopping cart or add to an existing shopping cart. Either coupon or bookable must be sent in the body of the request.
      summary: Create a new booking.
      tags:
        - Bookings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '../components/schema/bookings.yaml#/components/schemas/BookingCreateActivity'
                - $ref: '../components/schema/bookings.yaml#/components/schemas/BookingCreateCoupon'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      bookings:
                        $ref: '../components/schema/bookings.yaml#/components/schemas/BookingCreateResponse'
        4XX:
          $ref: '../components/schema/errors.yaml#/components/responses/4XX'
        default:
          $ref: '../components/schema/errors.yaml#/components/responses/Default'

    get:
      operationId: BookingsGetAll
      summary: Get all bookings.
      tags:
        - Bookings
      parameters:
        - $ref: '../components/commons/query.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons/query.yaml#/components/parameters/currency'
        - $ref: '../components/commons/query.yaml#/components/parameters/status'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      bookings:
                        type: array
                        items:
                          $ref: '../components/schema/bookings.yaml#/components/schemas/Booking'
        4XX:
          $ref: '../components/schema/errors.yaml#/components/responses/4XX'
        default:
          $ref: '../components/schema/errors.yaml#/components/responses/Default'

  /bookings/{booking_hash}:
    get:
      operationId: BookingsGetByHash
      summary: Get information about a booking
      tags:
        - Bookings
      parameters:
        - $ref: '../components/commons/path.yaml#/components/parameters/bookingHash'
        - $ref: '../components/commons/query.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons/query.yaml#/components/parameters/currency'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '../components/schema/bookings.yaml#/components/schemas/BookingsGetByHashResponse'
        4XX:
          $ref: '../components/schema/errors.yaml#/components/responses/4XX'
        default:
          $ref: '../components/schema/errors.yaml#/components/responses/Default'

    delete:
      operationId: bookingsDeleteByHash
      summary: Delete (Cancel) a booking.
      tags:
        - Bookings
      parameters:
        - $ref: '../components/commons/query.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons/query.yaml#/components/parameters/currency'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '../components/schema/bookings.yaml#/components/schemas/BookingDeleteResponse'
        4XX:
          $ref: '../components/schema/errors.yaml#/components/responses/4XX'
        default:
          $ref: '../components/schema/errors.yaml#/components/responses/Default'