openapi: 3.0.0
info:
  title: Paths for carts
  version: 1.0.0
paths:
  /carts:
    post:
      operationId: CartsConfirm
      summary: Confirm a shopping cart.
      tags:
        - Carts
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/externalReferenceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/schema/carts.yaml#/components/schemas/CartsConfirmRequest'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      shopping_cart:
                        oneOf:
                          - $ref: '../components/schema/carts.yaml#/components/schemas/CartsConfirmResponseConfirmed'
                          - $ref: '../components/schema/carts.yaml#/components/schemas/CartsConfirmResponseInPayment'
        4XX:
          $ref: '../components/schema/errors.yaml#/components/responses/4XX'
        default:
          $ref: '../components/schema/errors.yaml#/components/responses/Default'
  
  /carts/{shopping_cart_hash}:
    get:
      operationId: CartsGetByHash
      summary: Get information about a shopping cart.
      tags:
        - Carts
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/shoppingCartHash'
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      shopping_cart:
                        $ref: '../components/schema/carts.yaml#/components/schemas/CartsConfirmResponseConfirmed'
        4XX:
          $ref: '../components/schema/errors.yaml#/components/responses/4XX'
        default:
          $ref: '../components/schema/errors.yaml#/components/responses/Default'
