openapi: 3.0.0
info:
  title: Paths for categories
  version: 1.0.0
paths:
  /categories:
    get:
      operationId: CategoriesList
      summary: List all categories
      tags:
        - Categories
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
        - $ref: '../components/commons.yaml#/components/parameters/limit'
        - $ref: '../components/commons.yaml#/components/parameters/offset'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      categories:
                        type: array
                        items:
                          $ref: '../components/schema/category.yaml#/components/schemas/Category'
        4XX:
          $ref: '../components/schema/errors.yaml#/components/responses/4XX'
        default:
          $ref: '../components/schema/errors.yaml#/components/responses/Default'
  /categories/{category_id}:
    get:
      operationId: CategoriesGetById
      summary: Get information about a category
      tags:
        - Categories
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/categoryId'
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      categories:
                        type: array
                        items:
                          $ref: '../components/schema/category.yaml#/components/schemas/Category'
        4XX:
          $ref: '../components/schema/errors.yaml#/components/responses/4XX'
        default:
          $ref: '../components/schema/errors.yaml#/components/responses/Default'