openapi: 3.0.0
info:
  title: Paths for categories
  version: 1.0.0
paths:
  /categories:
    get:
      operationId: CategoriesList
      summary: List all categories
      tags:
        - Categories
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
        - $ref: '../components/commons.yaml#/components/parameters/limit'
        - $ref: '../components/commons.yaml#/components/parameters/offset'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../components/commons.yaml#/components/schemas/Category'
                example:
                  - category_id: 1
                    name: Tours
                    number_of_tours: 900
                  - category_id: 2
                    parent_id: 1
                    name: Lights tours
                    number_of_tours: 66
        400:
          description: Missing Parameters
        500:
          description: Server error
  /categories/{category_id}:
    get:
      operationId: CategoriesGetById
      summary: Get information about a category
      tags:
        - Categories
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/categoryId'
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../components/commons.yaml#/components/schemas/Category'
                example:
                  - category_id: 2
                    parent_id: 1
                    name: Lights tours
                    number_of_tours: 66
        400:
          description: Missing Parameters
        500:
          description: Server error