openapi: 3.0.0
info:
  title: Paths for configuration
paths:
  /configuration/{version}:
    get:
      operationId: configurationVersion
      summary: Get the configuration for an API version
      description: This endpoint is not based on the base url as it is version independent.
      tags:
        - Configuration
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/version'
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '../components/configuration.yaml#/components/schemas/ConfigurationVersionResponse'
        400:
          description: Missing Parameters
        500:
          description: Server error

  /configuration/payment:
    get:
      operationId: configurationPayment
      tags:
        - Configuration
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
        - $ref: '../components/commons.yaml#/components/parameters/country'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '../components/configuration.yaml#/components/schemas/ConfigurationPaymentResponse'
        400:
          description: Missing Parameters
        500:
          description: Server error