openapi: 3.0.0
info:
  title: Locations
  version: 1.0.0
  description: Query location data
paths:
  /locations:
    get:
      operationId: Locations
      tags:
        - Locations
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
        - $ref: '../components/commons.yaml#/components/parameters/sortfield'
        - $ref: '../components/commons.yaml#/components/parameters/offset'
        - $ref: '../components/commons.yaml#/components/parameters/preformatted'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      reviews:
                        type: object
                        properties:
                          outline:
                            $ref: '../components/schema/reviews.yaml#/components/schemas/Outline'
                          review_items:
                            $ref: '../components/schema/reviews.yaml#/components/schemas/ReviewItems'

        400:
          description: Missing Parameters
        500:
          description: Server error