openapi: 3.0.2
info:
  title: Paths for options
  version: 1.0.0
paths:
  /{version}/options/{option_id}:
    get:
      operationId: OptionsGetById
      description: Find a Tour Option by ID. The result will be an array of tour options. But the array will only contain one single tour option.
      tags:
        - Options
      parameters:
        - $ref: "../components/commons/path.yaml#/components/parameters/version"
        - $ref: "../components/commons/path.yaml#/components/parameters/optionId"
        - $ref: "../components/commons/query.yaml#/components/parameters/cntLanguage"
        - $ref: "../components/commons/query.yaml#/components/parameters/currency"
        - $ref: "../components/commons/query.yaml#/components/parameters/dates"
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: "../components/schema/metadata.yaml#/components/schemas/MetaData"
                  data:
                    type: object
                    properties:
                      tour_options:
                        type: array
                        items:
                          $ref: "../components/schema/option.yaml#/components/schemas/TourOption"
        4XX:
          $ref: "../components/schema/errors.yaml#/components/responses/4XX"
        default:
          $ref: "../components/schema/errors.yaml#/components/responses/Default"
