openapi: 3.0.2
info:
  title: Reviews
  version: 1.0.0
  description: Find reviews for a tour.
paths:
  /{version}/reviews/tour/{tour_id}:
    get:
      operationId: Reviews
      tags:
        - Reviews
      parameters:
        - $ref: "../components/commons/path.yaml#/components/parameters/version"
        - $ref: "../components/commons/path.yaml#/components/parameters/tourId"
        - $ref: "../components/commons/query.yaml#/components/parameters/cntLanguage"
        - $ref: "../components/commons/query.yaml#/components/parameters/currency"
        - $ref: "#/components/parameters/date"
        - $ref: "#/components/parameters/sortfield"
        - $ref: "../components/commons/query.yaml#/components/parameters/sortdirection"
        - $ref: "../components/commons/query.yaml#/components/parameters/limit"
        - $ref: "../components/commons/query.yaml#/components/parameters/offset"
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: "../components/schema/metadata.yaml#/components/schemas/MetaData"
                  data:
                    type: object
                    properties:
                      reviews:
                        type: object
                        properties:
                          outline:
                            $ref: "../components/schema/reviews.yaml#/components/schemas/Outline"
                          review_items:
                            $ref: "../components/schema/reviews.yaml#/components/schemas/ReviewItems"
        4XX:
          $ref: "../components/schema/errors.yaml#/components/responses/ErrorResponse"
        default:
          $ref: "../components/schema/errors.yaml#/components/responses/Default"
components:
  parameters:
    sortfield:
      description: Defines the sort field.
      in: query
      name: sortfield
      required: false
      schema:
        enum:
          - rating
          - date
        type: string
    date:
      description: Defines the date of the oldest review that should be returned.
      in: query
      name: date
      required: false
      schema:
        $ref: "#/components/schemas/Datetime"
  schemas:
    Datetime:
      $ref: "../components/commons/fields.yaml#/components/schemas/Datetime"