openapi: 3.0.0
info:
  title: Reviews
  version: 1.0.0
  description: Find reviews for a tour.
paths:
  /reviews/tour/{tour_id}:
    get:
      operationId: Reviews
      tags:
        - Reviews
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/tourId'
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
        - $ref: '../components/commons.yaml#/components/parameters/sortfield'
        - $ref: '../components/commons.yaml#/components/parameters/sortdirection'
        - $ref: '../components/commons.yaml#/components/parameters/limit'
        - $ref: '../components/commons.yaml#/components/parameters/offset'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      reviews:
                        type: object
                        properties:
                          outline:
                            $ref: '../components/schema/reviews.yaml#/components/schemas/Outline'
                          review_items:
                            $ref: '../components/schema/reviews.yaml#/components/schemas/ReviewItems'

        400:
          description: Missing Parameters
        500:
          description: Server error