openapi: 3.0.0
info:
  title: Paths for tours
  version: 1.0.0
paths:
  /tours:
    get:
      operationId: ToursQuery
      summary: Search for tours by different parameters such as a query or geographical coordinates.
      tags:
        - Tours
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
        - $ref: '../components/commons.yaml#/components/parameters/preformatted'
        - $ref: '../components/commons.yaml#/components/parameters/q'
        - $ref: '../components/commons.yaml#/components/parameters/coordinates'
        - $ref: '../components/commons.yaml#/components/parameters/date'
        - $ref: '../components/commons.yaml#/components/parameters/condLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/price'
        - $ref: '../components/commons.yaml#/components/parameters/categories'
        - $ref: '../components/commons.yaml#/components/parameters/rating'
        - $ref: '../components/commons.yaml#/components/parameters/duration'
        - $ref: '../components/commons.yaml#/components/parameters/flags'
        - $ref: '../components/commons.yaml#/components/parameters/sortfield'
        - $ref: '../components/commons.yaml#/components/parameters/sortdirection'
        - $ref: '../components/commons.yaml#/components/parameters/limit'
        - $ref: '../components/commons.yaml#/components/parameters/offset'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      tours:
                        type: array
                        items:
                          $ref: '../components/schema/tour.yaml#/components/schemas/Tour'
        400:
          description: Missing Parameters
        500:
          description: Server error
  
  /tours/{tour_id}:
    get:
      operationId: ToursByIdQuery
      summary: Search for tours by id
      tags:
        - Tours
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/tourId'
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
        - $ref: '../components/commons.yaml#/components/parameters/preformatted'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      tours:
                        type: array
                        items:
                          $ref: '../components/schema/tour.yaml#/components/schemas/Tour'
                    
        400:
          description: Missing Parameters
        500:
          description: Server error
  
  /tours/{tour_id}/availabilities:
    get:
      operationId: ToursByIdAvailabilities
      summary: Search for tours by id
      tags:
        - Tours
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/tourId'
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
        - $ref: '../components/commons.yaml#/components/parameters/date'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      availabilities:
                        type: array
                        items:
                          $ref: '../components/schema/availabilities.yaml#/components/schemas/Availabilities'

        400:
          description: Missing Parameters
        500:
          description: Server error
  
  /tours/{tour_id}/options:
    get:
      operationId: ToursByIdOptions
      summary: Find all options of a tour.
      tags:
        - Tours
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/tourId'
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _metadata:
                    $ref: '../components/schema/metadata.yaml#/components/schemas/MetaData'
                  data:
                    type: object
                    properties:
                      tour_options:
                        type: array
                        items:
                          $ref: '../components/schema/tour.yaml#/components/schemas/TourOption'

        400:
          description: Missing Parameters
        500:
          description: Server error
