openapi: 3.0.0
info:
  title: Paths for tours
  version: 1.0.0
paths:
  /tours:
    get:
      operationId: ToursQuery
      summary: Search for tours by different parameters such as a query or geographical coordinates.
      tags:
        - Tours
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
        - $ref: '../components/commons.yaml#/components/parameters/q'
        - $ref: '../components/commons.yaml#/components/parameters/coordinates'
        - $ref: '../components/commons.yaml#/components/parameters/date'
        - $ref: '../components/commons.yaml#/components/parameters/condLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/price'
        - $ref: '../components/commons.yaml#/components/parameters/categories'
        - $ref: '../components/commons.yaml#/components/parameters/rating'
        - $ref: '../components/commons.yaml#/components/parameters/duration'
        - $ref: '../components/commons.yaml#/components/parameters/flags'
        - $ref: '../components/commons.yaml#/components/parameters/sortfield'
        - $ref: '../components/commons.yaml#/components/parameters/sortdirection'
        - $ref: '../components/commons.yaml#/components/parameters/limit'
        - $ref: '../components/commons.yaml#/components/parameters/offset'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/bookings.yaml#/components/schemas/BookingCreateRequest'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '../components/bookings.yaml#/components/schemas/BookingCreateResponse'
        400:
          description: Missing Parameters
        500:
          description: Server error
