openapi: 3.0.0
info:
  title: Paths for tours
paths:
  /tours:
    get:
      operationId: ToursQuery
      summary: Search for tours by different parameters such as a query or geographical coordinates.
      tags:
        - Tours
      parameters:
        - $ref: '../components/commons.yaml#/components/parameters/cntLanguage'
        - $ref: '../components/commons.yaml#/components/parameters/currency'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/bookings.yaml#/components/schemas/BookingCreateRequest'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '../components/bookings.yaml#/components/schemas/BookingCreateResponse'
        400:
          description: Missing Parameters
        500:
          description: Server error
